import type {
  HandoverDraft,
  HandoverRecordData,
  HandoverTask,
  HistoricalAssessmentEntry,
  MonitoringEntry,
  ProjectHealthEntry,
  RosterMember,
  ShiftSwapRequest,
  Ticket,
} from "./types";

export const projects: ProjectHealthEntry[] = [
  { name: "SM", status: "Needs Attention", detail: "1 pengecualian", tone: "warning" },
  { name: "B2B", status: "Needs Attention", detail: "Pemeriksaan Kafka", tone: "warning" },
  { name: "USIEM", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "MB", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "EPC", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "DM", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "UNEM", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
];

export const attentionItems = [
  {
    project: "SM",
    title: "Queue ActiveMQ 228 memerlukan validasi",
    note: "Penumpukan queue dilaporkan pada checkpoint 18:00. Belum ada konfirmasi dari penanggung jawab.",
    time: "4 jam lalu",
    tone: "warning" as const,
    tag: "Queue",
  },
  {
    project: "B2B",
    title: "Aliran pesan tidak ada pada topik b2b-f…",
    note: "Terdeteksi saat validasi Kafka UI. Periksa kesehatan producer sebelum checkpoint berikutnya.",
    time: "4 jam lalu",
    tone: "warning" as const,
    tag: "Kafka",
  },
  {
    project: "EPC Tools",
    title: "Satu permintaan ad-hoc masih berlangsung",
    note: "Tinjau tugas approval entities sebelum handover shift.",
    time: "1 jam lalu",
    tone: "info" as const,
    tag: "Ticket",
  },
];

export const monitoringSchedule: MonitoringEntry[] = [
  { time: "13:00", project: "EPC Core", task: "Status layanan Catalog & Order", owner: "Mhd. Galih Khairi", state: "Done", tone: "success" },
  { time: "14:00", project: "APH", task: "Output Rate & Consumer Rate per PoP", owner: "Kristina Marbun", state: "Done", tone: "success" },
  { time: "15:00", project: "DM", task: "Device quota LintasArta", owner: "Kristina Marbun", state: "Done", tone: "success" },
  { time: "16:00", project: "UNEM", task: "Layanan & alert Grafana", owner: "M. Ihsanul Arifin", state: "Done", tone: "success" },
  { time: "17:00", project: "SM/ActiveMQ", task: "Queue fulldecode smng109", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning" },
  { time: "18:00", project: "B2B", task: "Disk usage /apps pv-bbsvsoe1", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning" },
  { time: "19:00", project: "USIEM", task: "Graylog input SIEM stream", owner: "Agnes", state: "Done", tone: "success" },
  { time: "20:00", project: "MB", task: "Push notification queue", owner: "Agnes", state: "Done", tone: "success" },
  { time: "21:00", project: "B2B", task: "Traffic topik Kafka", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", overview: true },
  { time: "21:00", project: "DM", task: "Utilisasi CPU Grafana", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "22:00", project: "SM", task: "Queue ActiveMQ 228 · 71 · 68", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", overview: true },
  { time: "22:00", project: "USIEM", task: "Graylog & Dashboard SIEM", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "22:00", project: "EPC Core", task: "Status layanan Catalog", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "22:00", project: "UNEM", task: "Layanan & alert Grafana", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "23:00", project: "Handover", task: "Tinjauan kesiapan shift malam", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true },
];

export const monitoringSystems = ["ActiveMQ", "Kafka", "Grafana", "Graylog", "Disk Usage"] as const;

export const seedHistoricalAssessments: HistoricalAssessmentEntry[] = [
  // Today (2026-08-31)
  {
    id: "hist-31-1300",
    date: "2026-08-31",
    time: "13:00",
    project: "EPC Core",
    task: "Status layanan Catalog & Order",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Semua pod catalog berjalan normal, error rate 0.01%.",
  },
  {
    id: "hist-31-1400",
    date: "2026-08-31",
    time: "14:00",
    project: "APH",
    task: "Output Rate & Consumer Rate per PoP",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Traffic PoP 1-4 stabil rata-rata 12.4k req/sec.",
  },
  {
    id: "hist-31-1500",
    date: "2026-08-31",
    time: "15:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Sinkronisasi quota berjalan lancar, tidak ada perangkat over-limit.",
  },
  {
    id: "hist-31-1600",
    date: "2026-08-31",
    time: "16:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Dashboard Grafana sehat, latency P95 di bawah 120ms.",
  },
  {
    id: "hist-31-1700",
    date: "2026-08-31",
    time: "17:00",
    project: "SM/ActiveMQ",
    task: "Queue fulldecode smng109",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Queue fulldecode meningkat ke 4.800 pesan. Eskalasi ticket #86d40cxuk.",
  },
  {
    id: "hist-31-1800",
    date: "2026-08-31",
    time: "18:00",
    project: "B2B",
    task: "Disk usage /apps pv-bbsvsoe1",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Disk /apps mencapai 92.4%. Pembersihan temporary files dilakukan.",
  },
  {
    id: "hist-31-1900",
    date: "2026-08-31",
    time: "19:00",
    project: "USIEM",
    task: "Graylog input SIEM stream",
    owner: "Agnes",
    verdict: "ok",
    note: "Throughput Graylog 45.000 msg/s, buffer memory aman.",
  },
  {
    id: "hist-31-2000",
    date: "2026-08-31",
    time: "20:00",
    project: "MB",
    task: "Push notification queue",
    owner: "Agnes",
    verdict: "ok",
    note: "Queue push notification kosong, delivery rate 99.8%.",
  },
  // Yesterday (2026-08-30)
  {
    id: "hist-30-2200",
    date: "2026-08-30",
    time: "22:00",
    project: "EPC Core",
    task: "Memory Leak pada Catalog Service Pods",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Crashloop terdeteksi pada pod catalog, eskalasi L3 ticket #86d40esc2.",
  },
  {
    id: "hist-30-2100",
    date: "2026-08-30",
    time: "21:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Consumer lag normal di bawah 1.500 pesan.",
  },
  {
    id: "hist-30-1900",
    date: "2026-08-30",
    time: "19:00",
    project: "USIEM",
    task: "Graylog & Dashboard SIEM",
    owner: "Agnes",
    verdict: "ok",
    note: "Semua stream input SIEM aktif tanpa error rate.",
  },
  {
    id: "hist-30-1600",
    date: "2026-08-30",
    time: "16:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "Galih Khairi",
    verdict: "ok",
    note: "Cluster node utilization merata pada kisaran 65%.",
  },
  {
    id: "hist-30-1400",
    date: "2026-08-30",
    time: "14:00",
    project: "APH",
    task: "Rebalance Consumer Area 1 CGNAT",
    owner: "Pangondion Kurniawan",
    verdict: "nok",
    note: "Egress listener throttling pada Area 1, konfigurasi disesuaikan #86d40y02a.",
  },
  // 29 Aug 2026
  {
    id: "hist-29-2000",
    date: "2026-08-29",
    time: "20:00",
    project: "SM",
    task: "Queue ActiveMQ 228",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Kondisi queue normal, 120 pesan pending terproses.",
  },
  {
    id: "hist-29-1700",
    date: "2026-08-29",
    time: "17:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Quota status sync sempurna.",
  },
];

export function getOwnerRole(name: string): string {
  const normalized = name.toLowerCase().trim();
  if (normalized.includes("galih")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("pangondion")) return "Shift Lead (Shift Malam)";
  if (normalized.includes("kurnia")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("ihsanul") || normalized.includes("arifin")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("marbun") || normalized.includes("kristina")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("agnes")) return "L2 Specialist (Shift Malam)";
  if (normalized.includes("iqbal")) return "L2 Specialist (Shift Malam)";
  if (normalized.includes("sarah")) return "Incident Coordinator (Shift Malam)";
  if (normalized.includes("bagas")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("dimas")) return "Infrastructure Engineer (Shift Pagi)";
  if (normalized.includes("malam")) return "NOC Shift Malam Team";
  return "Operator NOC (Shift Malam)";
}

export const seedTickets: Ticket[] = [
  // ── Today: 2026-08-31 ──
  {
    id: "86d4054rh",
    subject: "[EPC Tools] Tambah parameter baru untuk FMC",
    project: "EPC Tools",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Pangondion Kurniawan",
    status: "Active",
    created: "21:00",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 1.5,
    responseMinutes: 12,
    slaTargetMinutes: 120,
    description: "Permintaan konfigurasi parameter ambang FMC tambahan untuk mesin validasi EPC.",
    history: [
      { time: "21:00", action: "Ticket dibuat oleh operator", author: "Pangondion Kurniawan" },
      { time: "21:15", action: "Status diperbarui menjadi Active", author: "Pangondion Kurniawan" },
    ],
  },
  {
    id: "86d40esc1",
    subject: "[USIEM] Latency Spike pada Kafka SIEM Pipeline",
    project: "USIEM",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Mhd. Galih Khairi",
    status: "Escalated",
    created: "19:15",
    date: "2026-08-31",
    shift: "Malam",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Reza Rahardian (L2)",
    escalatedAt: "20:00",
    agingHours: 4.8,
    responseMinutes: 8,
    slaTargetMinutes: 60,
    rootCauseCategory: "Kafka Broker Sync",
    description: "Penumpukan lag consumer Kafka melebihi threshold 50.000 messages/sec, diekskalasikan ke tim infrastruktur L2.",
    history: [
      { time: "19:15", action: "Alert trigger terdeteksi", author: "Mhd. Galih Khairi" },
      { time: "20:00", action: "Dieskalasikan ke Reza Rahardian (L2)", author: "Mhd. Galih Khairi" },
    ],
  },
  {
    id: "86d40eqn1",
    subject: "[EPC Tools] Validasi approval entities",
    project: "EPC Tools",
    severity: "Medium",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "20:08",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 15,
    resolutionMinutes: 37,
    slaTargetMinutes: 60,
    description: "Validasi selesai untuk seluruh endpoint approval entities.",
    history: [
      { time: "20:08", action: "Ticket dibuat", author: "Pangondion Kurniawan" },
      { time: "20:45", action: "Masalah diselesaikan dan ditutup", author: "Pangondion Kurniawan" },
    ],
  },
  {
    id: "86d40cxuk",
    subject: "[SM] Transfer file buffer LTE",
    project: "SM",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "18:20",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 10,
    resolutionMinutes: 40,
    slaTargetMinutes: 120,
    description: "File buffer log LTE ditransfer ke node arsip sekunder.",
    history: [
      { time: "18:20", action: "Ticket dibuat", author: "Mhd. Galih Khairi" },
      { time: "19:00", action: "Transfer selesai dan checksum tervalidasi", author: "Mhd. Galih Khairi" },
    ],
  },
  {
    id: "86d40b9yh",
    subject: "[USIEM] Restart gateway log SIEM",
    project: "USIEM",
    severity: "Low",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "16:29",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 5,
    resolutionMinutes: 20,
    slaTargetMinutes: 60,
    description: "Restart gateway rutin setelah akumulasi memori socket minor.",
    history: [{ time: "16:29", action: "Gateway berhasil di-restart", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40bebu",
    subject: "[MB] Kirim event notifikasi push",
    project: "MB",
    severity: "Low",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "16:21",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 8,
    resolutionMinutes: 18,
    slaTargetMinutes: 60,
    description: "Laju queue pengiriman push notification mobile terverifikasi.",
    history: [{ time: "16:21", action: "Kondisi queue nominal terverifikasi", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40m01x",
    subject: "[B2B] Disk Space Alert pv-bbsvsoe1-ctl08 (>92%)",
    project: "B2B",
    severity: "High",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "03:40",
    date: "2026-08-31",
    shift: "Subuh",
    agingHours: 2.2,
    responseMinutes: 6,
    slaTargetMinutes: 60,
    description: "Kapasitas partisi /apps meningkat pesat saat pembersihan log malam.",
    history: [{ time: "03:40", action: "Pembersihan partisi sementara dimulai", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40dm01",
    subject: "[DM] Polling SNMP Over-Threshold PoP Balikpapan",
    project: "DM",
    severity: "Medium",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "10:15",
    date: "2026-08-31",
    shift: "Pagi",
    responseMinutes: 7,
    resolutionMinutes: 28,
    slaTargetMinutes: 60,
    description: "Normalisasi packet loss SNMP pada router edge Balikpapan.",
    history: [{ time: "10:15", action: "Route flapping distabilkan", author: "Kristina Marbun" }],
  },
  {
    id: "86d40un01",
    subject: "[UNEM] Penambahan Alert Rules Prometheus Disk Latency",
    project: "UNEM",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "11:40",
    date: "2026-08-31",
    shift: "Pagi",
    responseMinutes: 14,
    resolutionMinutes: 42,
    slaTargetMinutes: 120,
    description: "Aturan alerting baru untuk I/O wait waktu respon disk terpasang.",
    history: [{ time: "11:40", action: "Alert rule deployed", author: "Kristina Marbun" }],
  },

  // ── Yesterday: 2026-08-30 ──
  {
    id: "86d40y02a",
    subject: "[APH] Rebalance Consumer Area 1 CGNAT F5",
    project: "APH",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "14:10",
    date: "2026-08-30",
    shift: "Pagi",
    responseMinutes: 14,
    resolutionMinutes: 52,
    slaTargetMinutes: 60,
    description: "Penyesuaian distribusi rate Egress F5 untuk menghindari throttling.",
    history: [{ time: "14:10", action: "Konfigurasi rebalance diterapkan", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40esc2",
    subject: "[EPC Tools] Memory Leak pada Catalog Service Pods",
    project: "EPC Tools",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "22:15",
    date: "2026-08-30",
    shift: "Malam",
    escalationLevel: "L3 Incident Coordinator",
    escalatedTo: "Dimas Suryo (L3 Lead)",
    escalatedAt: "23:00",
    responseMinutes: 10,
    resolutionMinutes: 75,
    slaTargetMinutes: 60,
    rootCauseCategory: "Memory Saturation",
    description: "Pod catalog crash berulang di cluster k8s node-04, eskalasi L3 koordinasi dengan dev infra.",
    history: [
      { time: "22:15", action: "Crashloop terdeteksi", author: "M. Ihsanul Arifin" },
      { time: "23:30", action: "Patch buffer hotspot diterapkan", author: "Dimas Suryo" },
    ],
  },
  {
    id: "86d40sm02",
    subject: "[SM] Penumpukan Queue ActiveMQ smng109",
    project: "SM",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "17:45",
    date: "2026-08-30",
    shift: "Malam",
    responseMinutes: 6,
    resolutionMinutes: 48,
    slaTargetMinutes: 60,
    description: "Consumer rate ActiveMQ ditingkatkan untuk mengosongkan 4.200 antrean log.",
    history: [{ time: "17:45", action: "Thread consumer dinaikkan", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40b2b02",
    subject: "[B2B] Re-sync Partisi Topic Kafka Billing",
    project: "B2B",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "08:30",
    date: "2026-08-30",
    shift: "Pagi",
    responseMinutes: 11,
    resolutionMinutes: 35,
    slaTargetMinutes: 60,
    description: "Leader partition rebalance pada cluster Kafka B2B.",
    history: [{ time: "08:30", action: "Rebalance sukses", author: "Agnes" }],
  },

  // ── Earlier This Week: 2026-08-29 ──
  {
    id: "86d4029a1",
    subject: "[MB] Database Connection Pool Saturation",
    project: "MB",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "19:20",
    date: "2026-08-29",
    shift: "Malam",
    responseMinutes: 8,
    resolutionMinutes: 41,
    slaTargetMinutes: 60,
    description: "Idle connection cleanup pada pool database notification service.",
    history: [{ time: "19:20", action: "Pool connection recycled", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d4029a2",
    subject: "[APH] Audit Egress Traffic Roaming Data",
    project: "APH",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "14:00",
    date: "2026-08-29",
    shift: "Pagi",
    responseMinutes: 18,
    resolutionMinutes: 50,
    slaTargetMinutes: 120,
    description: "Rekap traffic harian PoP 1 sampai 4 untuk laporan audit.",
    history: [{ time: "14:00", action: "Data export tervalidasi", author: "Kristina Marbun" }],
  },
  {
    id: "86d4029a3",
    subject: "[L2] Penyusunan RCA Incident Intermittent Gateway",
    project: "L2",
    severity: "Medium",
    type: "Other",
    category: "Knowledge Management & Documentation",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "11:15",
    date: "2026-08-29",
    shift: "Pagi",
    responseMinutes: 12,
    resolutionMinutes: 65,
    slaTargetMinutes: 120,
    description: "Penyusunan Root Cause Analysis untuk review manajemen insiden.",
    history: [{ time: "11:15", action: "Dokumen RCA diunggah", author: "Pangondion Kurniawan" }],
  },

  // ── Earlier This Week: 2026-08-28 ──
  {
    id: "86d40w03k",
    subject: "[DM] Sinkronisasi Device Quota LintasArta",
    project: "DM",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "09:30",
    date: "2026-08-28",
    shift: "Pagi",
    responseMinutes: 9,
    resolutionMinutes: 45,
    slaTargetMinutes: 60,
    description: "Database sync over-quota pulih setelah reload daemon worker.",
    history: [{ time: "09:30", action: "Reload worker daemon", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d4028b1",
    subject: "[USIEM] Pembersihan Indeks Elastic Log Expired",
    project: "USIEM",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "02:15",
    date: "2026-08-28",
    shift: "Subuh",
    responseMinutes: 10,
    resolutionMinutes: 30,
    slaTargetMinutes: 120,
    description: "Indeks lama dirotasi ke cold storage untuk membebaskan 1.2 TB.",
    history: [{ time: "02:15", action: "Index lifecycle management executed", author: "Agnes" }],
  },
  {
    id: "86d4028b2",
    subject: "[EPC Tools] Export Rekap Validasi Order Bulanan",
    project: "EPC Tools",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "15:40",
    date: "2026-08-28",
    shift: "Pagi",
    responseMinutes: 12,
    resolutionMinutes: 25,
    slaTargetMinutes: 60,
    description: "Ekspor rekap query analitik untuk divisi EPC.",
    history: [{ time: "15:40", action: "File CSV dikirim", author: "Mhd. Galih Khairi" }],
  },

  // ── Earlier This Week: 2026-08-27 ──
  {
    id: "86d4027a1",
    subject: "[SM] Upstream Telco SS7 Gateway Timeouts",
    project: "SM",
    severity: "Critical",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "20:10",
    date: "2026-08-27",
    shift: "Malam",
    responseMinutes: 7,
    resolutionMinutes: 88,
    slaTargetMinutes: 60,
    rootCauseCategory: "Upstream Vendor / ISP",
    description: "Timeout koneksi gateway SS7 dari upstream provider; switchover ke link cadangan.",
    history: [
      { time: "20:10", action: "Incident terdeteksi", author: "Pangondion Kurniawan" },
      { time: "21:38", action: "Failover tuntas", author: "Pangondion Kurniawan" },
    ],
  },
  {
    id: "86d4027a2",
    subject: "[B2B] Tambah Node Kafka Broker 04",
    project: "B2B",
    severity: "Medium",
    type: "Change Request",
    category: "Change Request",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "13:00",
    date: "2026-08-27",
    shift: "Pagi",
    responseMinutes: 15,
    resolutionMinutes: 55,
    slaTargetMinutes: 120,
    description: "Pemasangan dan join cluster node broker Kafka tambahan.",
    history: [{ time: "13:00", action: "Broker joined cluster", author: "Kristina Marbun" }],
  },
  {
    id: "86d4027a3",
    subject: "[UNEM] Audit Dashboard Grafana NOC Shift Room",
    project: "UNEM",
    severity: "Low",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "09:00",
    date: "2026-08-27",
    shift: "Pagi",
    responseMinutes: 10,
    resolutionMinutes: 30,
    slaTargetMinutes: 60,
    description: "Pemeriksaan konsistensi metrik panel TV monitoring.",
    history: [{ time: "09:00", action: "Verifikasi OK", author: "M. Ihsanul Arifin" }],
  },

  // ── Earlier This Week: 2026-08-26 & 2026-08-25 ──
  {
    id: "86d4026a1",
    subject: "[APH] Spike Packet Drop pada PoP Jakarta 2",
    project: "APH",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "16:45",
    date: "2026-08-26",
    shift: "Malam",
    responseMinutes: 6,
    resolutionMinutes: 34,
    slaTargetMinutes: 60,
    description: "Penyesuaian MTU pada switch interface PoP Jakarta 2.",
    history: [{ time: "16:45", action: "MTU tuned to 9000 jumbo frame", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d4026a2",
    subject: "[MB] Maintenance Sertifikat SSL Webhook Gateway",
    project: "MB",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "01:30",
    date: "2026-08-26",
    shift: "Subuh",
    responseMinutes: 12,
    resolutionMinutes: 28,
    slaTargetMinutes: 60,
    description: "Perpanjangan sertifikat TLS wildcard domain notification push.",
    history: [{ time: "01:30", action: "Certificate renewed and nginx reloaded", author: "Agnes" }],
  },
  {
    id: "86d4025a1",
    subject: "[EPC Tools] Konfigurasi Filter Rule Automation Baru",
    project: "EPC Tools",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "14:20",
    date: "2026-08-25",
    shift: "Pagi",
    responseMinutes: 16,
    resolutionMinutes: 39,
    slaTargetMinutes: 120,
    description: "Rule filter validasi nomor MSISDN VIP ditambahkan.",
    history: [{ time: "14:20", action: "Rules activated in engine", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d4025a2",
    subject: "[USIEM] Alarm Disk Warning pada Node SIEM-02",
    project: "USIEM",
    severity: "High",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "04:10",
    date: "2026-08-25",
    shift: "Subuh",
    responseMinutes: 9,
    resolutionMinutes: 44,
    slaTargetMinutes: 60,
    description: "Pembersihan dump log gzip lama di /data/siem.",
    history: [{ time: "04:10", action: "Disk usage down to 64%", author: "M. Ihsanul Arifin" }],
  },

  // ── Open / Backlog Aging Spectrum representation ──
  {
    id: "86d40bg01",
    subject: "[L2] Koordinasi Perbaikan Skema Partisi Database Arsip",
    project: "L2",
    severity: "Medium",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Galih Khairi",
    status: "Pending",
    created: "10:00",
    date: "2026-08-29",
    shift: "Pagi",
    agingHours: 52.0,
    responseMinutes: 15,
    slaTargetMinutes: 120,
    description: "Menunggu jadwal maintenance window akhir pekan bersama tim DBA.",
    history: [{ time: "10:00", action: "Ticket dipending menunggu window maintenance", author: "Galih Khairi" }],
  },
  {
    id: "86d40bg02",
    subject: "[DM] Penggantian Modul Transceiver SFP Ruang Server DM",
    project: "DM",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Kristina Marbun",
    status: "Pending",
    created: "09:00",
    date: "2026-08-28",
    shift: "Pagi",
    agingHours: 76.5,
    responseMinutes: 22,
    slaTargetMinutes: 120,
    description: "Menunggu pengiriman suku cadang modul SFP dari vendor LintasArta.",
    history: [{ time: "09:00", action: "Vendor order placed", author: "Kristina Marbun" }],
  },

  // ── Last Month Baseline (July 2026) ──
  {
    id: "86d40p04m",
    subject: "[L2] Audit SOP Incident Coordinator Shift Handover",
    project: "L2",
    severity: "Low",
    type: "Other",
    category: "Knowledge Management & Documentation",
    owner: "Galih Khairi",
    status: "Closed",
    created: "11:00",
    date: "2026-07-15",
    shift: "Pagi",
    responseMinutes: 20,
    resolutionMinutes: 90,
    slaTargetMinutes: 120,
    description: "Dokumentasi SOP perbaikan matriks eskalasi diperbarui.",
    history: [{ time: "11:00", action: "Dokumen SOP diarsipkan ke Runbooks", author: "Galih Khairi" }],
  },
  {
    id: "86d40prev1",
    subject: "[UNEM] Penyesuaian Dashboard Grafana Core Services",
    project: "UNEM",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Galih Khairi",
    status: "Closed",
    created: "15:00",
    date: "2026-07-25",
    shift: "Pagi",
    responseMinutes: 18,
    resolutionMinutes: 60,
    slaTargetMinutes: 120,
    description: "Panel alerting Grafana ditambahkan untuk metrik CPU Core.",
    history: [{ time: "15:00", action: "Dashboard updated", author: "Galih Khairi" }],
  },
  {
    id: "86d40prev2",
    subject: "[SM] Patch Keamanan ActiveMQ Cluster",
    project: "SM",
    severity: "High",
    type: "Maintenance",
    category: "Maintenance",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "01:00",
    date: "2026-07-20",
    shift: "Subuh",
    responseMinutes: 10,
    resolutionMinutes: 50,
    slaTargetMinutes: 60,
    description: "Security patch rollover pada broker cluster.",
    history: [{ time: "01:00", action: "Patch applied", author: "M. Ihsanul Arifin" }],
  },
];

export const initialHandoverTasks: HandoverTask[] = [
  { id: 1, title: "Pemantauan Dump Automation EPC Tools", project: "EPC Tools", detail: "Perketat pemantauan Dump Automation. Pengecekan dapat menggunakan akun Teresa rosikin2011_x.", state: "repeat", completed: true },
  { id: 2, title: "Pengecekan Email L2 Support di akhir shift", project: "L2", detail: "Pastikan seluruh folder sudah dibaca dan tidak ada request yang terlewat.", state: "repeat", completed: true },
  { id: 3, title: "Monitoring penumpukan fulldecode SM", project: "SM", detail: "Pantau queue fulldecode pada ActiveMQ 228 dan direktori output smng109.", state: "repeat", completed: true },
  { id: 4, title: "Monitoring disk usage B2B Prod", project: "B2B", detail: "Pantau /apps pada pv-bbsvsoe1-ctl08-20:9100; informasikan ke Mas Alfiant apabila mencapai 98%.", state: "repeat", completed: true },
  { id: 5, title: "Monitoring performa APH per jam", project: "APH", detail: "Pantau Output Rate, APH Consumer Rate, serta Egress Listener F5 CGNAT Area 1 per PoP dan laporkan ke Teams APH.", state: "repeat", completed: true },
  { id: 6, title: "Report Repsoses file Excel SM", project: "SM", detail: "Kirim report hasil Repsoses dari tim Solusi ke grup WA SM-MB Support Tritronik pada pagi dan malam hari.", state: "repeat", completed: true },
  { id: 7, title: "Volume Roamware dan Backup SM", project: "SM", detail: "Lakukan pengisian di akhir shift serta monitoring total volume Huawei SGW.", state: "repeat", completed: true },
  { id: 8, title: "Dashboard LintasArta DM", project: "DM", detail: "Perhatikan all device quota / over quota usage; eskalasi langsung jika setelah pukul 01.00 data masih kosong.", state: "repeat", completed: true },
  { id: 9, title: "Perhitungan volume output data APH", project: "APH", detail: "Rekap output GGSN Ericsson, Huawei, ZTE dan UFP Huawei 5GC dalam volume serta events per hari.", state: "waiting", completed: false },
  { id: 10, title: "Report SM MonthlyHealth-SMMB", project: "SM", detail: "Pengerjaan materi Presentation MonthlyHealth-SMMB masih berlangsung.", state: "in-progress", completed: false },
];

export const initialHandoverRecord: HandoverRecordData = {
  sourceShift: "Subuh",
  targetShift: "Pagi",
  sourcePic: "Agnes",
  targetPic: "Galih, Natanael, Pangondion",
  monitoringSummary: "Pengecekan dan monitoring telah dilakukan serta dilaporkan di grup Telegram sesuai checkpoint yang ditentukan.",
  monitoringOwner: "Agnes",
  monitoredProjects: ["B2B", "DM", "EPC", "APH", "SM/ActiveMQ", "USIEM", "MB", "UNEM"],
  validationNote: "Galih, Natanael, dan Pangondion telah memeriksa hasil monitoring pada sesi handover.",
  findings: [
    {
      project: "USIEM",
      title: "Log direct MSS belum tampil",
      detail: "Log MSS Eric dan MSS Nokia sempat tertumpuk pada log distributor. Layanan telah di-restart dan tren penumpukan mulai menurun.",
      state: "waiting",
    },
    {
      project: "USIEM",
      title: "Input Graylog tidak menerima data",
      detail: "Input siem-fw-diameter-event, siem-fw-ss7-event, dan siem-fw-gtp-event tidak menerima data; sedang ditindaklanjuti di grup USIEM DevOps.",
      state: "in-progress",
    },
  ],
  tasks: initialHandoverTasks,
};

export const teamMembers = [
  { name: "Mhd. Galih Khairi", role: "Koordinator" },
  { name: "Kristina Marbun", role: "Operator" },
  { name: "M. Ihsanul Arifin", role: "Operator" },
];

export const projectHealthWeekly = [
  { project: "SM", days: [96, 94, 92, 98, 95, 90, 93] },
  { project: "B2B", days: [97, 95, 99, 94, 92, 96, 91] },
  { project: "USIEM", days: [100, 99, 100, 98, 100, 99, 100] },
  { project: "MB", days: [100, 100, 98, 100, 99, 100, 100] },
  { project: "EPC Tools", days: [99, 100, 100, 97, 100, 100, 99] },
  { project: "DM", days: [98, 100, 99, 100, 97, 100, 100] },
  { project: "UNEM", days: [100, 98, 100, 100, 99, 100, 100] },
];

export function toDateInputValue(date = new Date()) {
  const timezoneOffset = date.getTimezoneOffset() * 60000;
  return new Date(date.getTime() - timezoneOffset).toISOString().slice(0, 10);
}

export function formatHandoverDate(value: string) {
  const parsed = new Date(`${value}T00:00:00`);
  return Number.isNaN(parsed.getTime())
    ? value
    : new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "long", year: "numeric" }).format(parsed);
}

export function nowClockLabel() {
  const now = new Date();
  return `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
}

export function makeTicketId() {
  return `86d4${Math.random().toString(36).slice(2, 7)}`;
}

export function createHandoverDraft(
  record: HandoverRecordData = initialHandoverRecord,
  date = toDateInputValue(),
): HandoverDraft {
  return {
    date,
    sourceShift: record.sourceShift,
    targetShift: record.targetShift,
    sourcePic: record.sourcePic,
    targetPic: record.targetPic,
    monitoringOwner: record.monitoringOwner,
    monitoredProjects: record.monitoredProjects.join(", "),
    monitoringSummary: record.monitoringSummary,
    validationNote: record.validationNote,
    findings: record.findings.map((finding) => ({ ...finding })),
    tasks: record.tasks.map((task) => ({ ...task })),
  };
}

export function initials(name: string | null | undefined) {
  if (!name?.trim()) return "??";
  return name
    .trim()
    .split(/\s+/)
    .map((part) => part[0] ?? "")
    .join("")
    .slice(0, 2)
    .toUpperCase() || "??";
}

/**
 * Canonical check for whether a ticket is considered "open" (in-progress).
 * Unifies the fragmented status checks scattered across the codebase.
 */
export function isOpenTicket(ticket: Ticket): boolean {
  const s = ticket.status.toLowerCase();
  return (
    s === "active" ||
    s === "aktivitas" ||
    s === "activity" ||
    s === "open" ||
    s === "pending" ||
    s === "menunggu" ||
    s === "escalated" ||
    s === "eskalasi" ||
    s === "re-open"
  );
}

/** Safe average that returns 0 for empty arrays instead of NaN. */
export function safeAverage(values: number[]): number {
  if (!values.length) return 0;
  return Math.round(values.reduce((sum, v) => sum + v, 0) / values.length);
}

// ── Dynamic date utilities (replaces hardcoded "2026-08-31" etc.) ──

/** Returns today's date in YYYY-MM-DD format, pinned to WIB (UTC+7). */
export function getTodayWIB(): string {
  const now = new Date();
  // Convert to WIB by adding UTC+7 offset
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs);
  return wib.toISOString().slice(0, 10);
}

/** Returns yesterday's date in YYYY-MM-DD, pinned to WIB. */
export function getYesterdayWIB(): string {
  const now = new Date();
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs - 86_400_000);
  return wib.toISOString().slice(0, 10);
}

/** Returns start of current ISO week (Monday) in YYYY-MM-DD, pinned to WIB. */
export function getStartOfWeekWIB(): string {
  const now = new Date();
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs);
  const day = wib.getDay(); // 0=Sun
  const diff = day === 0 ? 6 : day - 1; // Monday=0
  wib.setDate(wib.getDate() - diff);
  return wib.toISOString().slice(0, 10);
}

/** Returns start of current month in YYYY-MM-DD, pinned to WIB. */
export function getStartOfMonthWIB(): string {
  const today = getTodayWIB();
  return today.slice(0, 8) + "01";
}

/** Returns start of previous ISO week (Monday) in YYYY-MM-DD. */
export function getStartOfLastWeekWIB(): string {
  const now = new Date();
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs);
  const day = wib.getDay();
  const diff = day === 0 ? 6 : day - 1;
  wib.setDate(wib.getDate() - diff - 7);
  return wib.toISOString().slice(0, 10);
}

/** Returns end of previous ISO week (Sunday) in YYYY-MM-DD. */
export function getEndOfLastWeekWIB(): string {
  const start = getStartOfLastWeekWIB();
  const d = new Date(start + "T00:00:00");
  d.setDate(d.getDate() + 6);
  return d.toISOString().slice(0, 10);
}

/** Returns YYYY-MM prefix for last month, pinned to WIB. */
export function getLastMonthPrefixWIB(): string {
  const today = getTodayWIB();
  const y = parseInt(today.slice(0, 4), 10);
  const m = parseInt(today.slice(5, 7), 10);
  const prevMonth = m === 1 ? 12 : m - 1;
  const prevYear = m === 1 ? y - 1 : y;
  return `${prevYear}-${String(prevMonth).padStart(2, "0")}`;
}

export const seedRosterMembers: RosterMember[] = [
  {
    id: "mem-1",
    name: "Galih Khairi",
    role: "Operator NOC",
    employeeId: "EMP-1048",
    email: "galih.khairi@company.id",
    phone: "+62 812-3456-7890",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "15 Jan 2024",
    avatarBg: "#2563eb",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 98.5,
      shiftsCompleted: 142,
      handoverScore: 99.2,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present", note: "On-time check-in, lead NOC console" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present", note: "Handover smoothly confirmed" },
      { date: "26 Aug", shift: "Shift Malam", status: "Present" },
      { date: "25 Aug", shift: "Shift Malam", status: "Present" },
      { date: "24 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-2",
    name: "Pangondion Kurniawan",
    role: "Shift Lead",
    employeeId: "EMP-1012",
    email: "pangondion.k@company.id",
    phone: "+62 813-8877-6655",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "01 Mar 2023",
    avatarBg: "#7c3aed",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 100,
      shiftsCompleted: 218,
      handoverScore: 99.8,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present", note: "Shift supervisor & escalation handler" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present" },
      { date: "26 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-3",
    name: "Kurnia Meidiyansyah",
    role: "Operator NOC",
    employeeId: "EMP-1055",
    email: "kurnia.m@company.id",
    phone: "+62 819-9011-2233",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "10 Feb 2024",
    avatarBg: "#059669",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 96.8,
      shiftsCompleted: 110,
      handoverScore: 97.5,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-4",
    name: "Muhammad Iqbal",
    role: "L2 Specialist",
    employeeId: "EMP-1029",
    email: "m.iqbal@company.id",
    phone: "+62 856-1122-3344",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "On Break",
    joinDate: "20 Jun 2023",
    avatarBg: "#d97706",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 97.0,
      shiftsCompleted: 165,
      handoverScore: 98.4,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present", note: "Break scheduled 19:30–20:15" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-5",
    name: "Sarah Wijaya",
    role: "Incident Coordinator",
    employeeId: "EMP-1008",
    email: "sarah.w@company.id",
    phone: "+62 811-2233-4455",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "12 Oct 2022",
    avatarBg: "#db2777",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 99.1,
      shiftsCompleted: 240,
      handoverScore: 99.5,
    },
    history: [
      { date: "28 Aug", shift: "Shift Pagi", status: "Present", note: "Incident bridge commander" },
    ],
  },
  {
    id: "mem-6",
    name: "Bagas Pratama",
    role: "Operator NOC",
    employeeId: "EMP-1062",
    email: "bagas.p@company.id",
    phone: "+62 817-4455-6677",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "05 May 2024",
    avatarBg: "#4f46e5",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 95.0,
      shiftsCompleted: 88,
      handoverScore: 96.0,
    },
    history: [
      { date: "28 Aug", shift: "Shift Subuh", status: "Present", note: "Early morning batch and monitoring checks" },
    ],
  },
  {
    id: "mem-7",
    name: "Dimas Anggoro",
    role: "Infrastructure Engineer",
    employeeId: "EMP-1033",
    email: "dimas.a@company.id",
    phone: "+62 821-3344-5566",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Off Duty",
    joinDate: "18 Aug 2023",
    avatarBg: "#0891b2",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 98.0,
      shiftsCompleted: 175,
      handoverScore: 98.9,
    },
    history: [
      { date: "28 Aug", shift: "Shift Pagi", status: "Present", note: "Completed morning DC routine" },
    ],
  },
  {
    id: "mem-8",
    name: "Annisa Rahmawati",
    role: "Operator NOC",
    employeeId: "EMP-1070",
    email: "annisa.r@company.id",
    phone: "+62 857-7788-9900",
    currentShift: "Cuti Tahunan (On Leave)",
    status: "On Leave",
    joinDate: "01 Jul 2024",
    avatarBg: "#ea580c",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sel", date: "25 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Rab", date: "26 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Kam", date: "27 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Jum", date: "28 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 96.0,
      shiftsCompleted: 45,
      handoverScore: 97.0,
    },
    history: [
      { date: "28 Aug", shift: "Annual Leave", status: "Leave", note: "Approved annual leave" },
    ],
  },
  {
    id: "mem-9",
    name: "Rizky Ramadhani",
    role: "Operator NOC",
    employeeId: "EMP-1072",
    email: "rizky.r@company.id",
    phone: "+62 812-7711-2233",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "15 Aug 2024",
    avatarBg: "#0284c7",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 97.5, shiftsCompleted: 62, handoverScore: 98.1 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-10",
    name: "Fajar Nugroho",
    role: "Incident Coordinator",
    employeeId: "EMP-1015",
    email: "fajar.n@company.id",
    phone: "+62 813-9988-7766",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "04 Jan 2023",
    avatarBg: "#8b5cf6",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 99.4, shiftsCompleted: 210, handoverScore: 99.7 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-11",
    name: "Dewi Sartika",
    role: "Operator NOC",
    employeeId: "EMP-1065",
    email: "dewi.s@company.id",
    phone: "+62 818-2233-4455",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "10 Jun 2024",
    avatarBg: "#ec4899",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 96.2, shiftsCompleted: 78, handoverScore: 96.9 },
    history: [{ date: "28 Aug", shift: "Shift Subuh", status: "Present" }],
  },
  {
    id: "mem-12",
    name: "Budi Santoso",
    role: "Shift Lead",
    employeeId: "EMP-1009",
    email: "budi.s@company.id",
    phone: "+62 811-3344-5566",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "12 Nov 2022",
    avatarBg: "#10b981",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 99.0, shiftsCompleted: 235, handoverScore: 99.4 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-13",
    name: "Maya Indira",
    role: "L2 Specialist",
    employeeId: "EMP-1031",
    email: "maya.i@company.id",
    phone: "+62 856-7788-9911",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "18 Sep 2023",
    avatarBg: "#6366f1",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 98.2, shiftsCompleted: 155, handoverScore: 98.7 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-14",
    name: "Dwi Cahyono",
    role: "Operator NOC",
    employeeId: "EMP-1068",
    email: "dwi.c@company.id",
    phone: "+62 817-6677-8899",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "20 May 2024",
    avatarBg: "#14b8a6",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 95.8, shiftsCompleted: 92, handoverScore: 96.5 },
    history: [{ date: "28 Aug", shift: "Shift Subuh", status: "Present" }],
  },
  {
    id: "mem-15",
    name: "Reza Pratama",
    role: "Infrastructure Engineer",
    employeeId: "EMP-1038",
    email: "reza.p@company.id",
    phone: "+62 822-1122-3344",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "05 Dec 2023",
    avatarBg: "#f59e0b",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 98.8, shiftsCompleted: 140, handoverScore: 99.1 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-16",
    name: "Eka Putri",
    role: "Operator NOC",
    employeeId: "EMP-1059",
    email: "eka.p@company.id",
    phone: "+62 819-4455-6677",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "15 Mar 2024",
    avatarBg: "#a855f7",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 97.2, shiftsCompleted: 104, handoverScore: 97.8 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-17",
    name: "Hendra Wijaya",
    role: "Incident Coordinator",
    employeeId: "EMP-1018",
    email: "hendra.w@company.id",
    phone: "+62 812-8899-0011",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "01 Feb 2023",
    avatarBg: "#ef4444",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 99.2, shiftsCompleted: 198, handoverScore: 99.3 },
    history: [{ date: "28 Aug", shift: "Shift Subuh", status: "Present" }],
  },
  {
    id: "mem-18",
    name: "Tiara Andini",
    role: "Operator NOC",
    employeeId: "EMP-1077",
    email: "tiara.a@company.id",
    phone: "+62 858-1122-3344",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "On Break",
    joinDate: "01 Sep 2024",
    avatarBg: "#06b6d4",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 96.5, shiftsCompleted: 42, handoverScore: 97.2 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-19",
    name: "Aditya Pratama",
    role: "L2 Specialist",
    employeeId: "EMP-1035",
    email: "aditya.p@company.id",
    phone: "+62 813-5566-7788",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "14 Oct 2023",
    avatarBg: "#3b82f6",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 98.6, shiftsCompleted: 172, handoverScore: 98.9 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-20",
    name: "Nadia Safitri",
    role: "Operator NOC",
    employeeId: "EMP-1082",
    email: "nadia.s@company.id",
    phone: "+62 878-9900-1122",
    currentShift: "Cuti Tahunan (On Leave)",
    status: "On Leave",
    joinDate: "20 Jul 2024",
    avatarBg: "#f97316",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sel", date: "25 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Rab", date: "26 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Kam", date: "27 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Jum", date: "28 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 95.5, shiftsCompleted: 38, handoverScore: 96.0 },
    history: [{ date: "28 Aug", shift: "Annual Leave", status: "Leave" }],
  },
];

export const seedSwapRequests: ShiftSwapRequest[] = [
  {
    id: "swap-1",
    requesterId: "mem-6",
    requesterName: "Bagas Pratama",
    targetMemberId: "mem-3",
    targetMemberName: "Kurnia Meidiyansyah",
    requestedDate: "29 Aug 2026",
    currentShift: "Shift Malam (16:00–00:30)",
    targetShift: "Shift Pagi (08:00–16:30)",
    reason: "Ada keperluan keluarga mendesak di pagi hari.",
    status: "Pending",
    createdAt: "28 Aug 18:40",
  },
  {
    id: "swap-2",
    requesterId: "mem-1",
    requesterName: "Galih Khairi",
    targetMemberId: "mem-7",
    targetMemberName: "Dimas Anggoro",
    requestedDate: "22 Aug 2026",
    currentShift: "Shift Pagi",
    targetShift: "Shift Malam",
    reason: "Penyesuaian jadwal maintenance datacenter.",
    status: "Approved",
    createdAt: "21 Aug 10:15",
  },
];
