import type {
  HandoverTask,
  HistoricalAssessmentEntry,
  MonitoringEntry,
  ProjectHealthEntry,
  Ticket,
} from "./types";
import { projects, monitoringSchedule, seedHistoricalAssessments, seedTickets, initialHandoverTasks } from "./data";
import { ClientOrganization, CLIENT_ORGANIZATIONS } from "../context/ClientContext";

export const EXTENDED_CLIENT_ORGANIZATIONS: readonly ClientOrganization[] = [
  ...CLIENT_ORGANIZATIONS,
  {
    id: "mandiri",
    name: "Bank Mandiri (Persero) Tbk",
    shortName: "Bank Mandiri",
    code: "BMRI",
    tagline: "Core Banking, Livin' Financial Superapp & Wholesale Kopra",
    avatarBg: "rgba(234, 179, 8, 0.16)",
    avatarColor: "#facc15",
    borderColor: "rgba(234, 179, 8, 0.35)",
    tier: "Mission Critical",
    systemsCount: 6,
  },
  {
    id: "bca",
    name: "PT Bank Central Asia Tbk",
    shortName: "BCA",
    code: "BCA",
    tagline: "High-Volume Switcher, myBCA & Real-Time Settlement",
    avatarBg: "rgba(59, 130, 246, 0.16)",
    avatarColor: "#60a5fa",
    borderColor: "rgba(59, 130, 246, 0.35)",
    tier: "Dedicated SLA",
    systemsCount: 8,
  },
  {
    id: "indosat",
    name: "Indosat Ooredoo Hutchison",
    shortName: "Indosat",
    code: "IOH",
    tagline: "National 4G/5G Transport & Enterprise Data Services",
    avatarBg: "rgba(244, 63, 94, 0.16)",
    avatarColor: "#fb7185",
    borderColor: "rgba(244, 63, 94, 0.35)",
    tier: "Enterprise NOC",
    systemsCount: 7,
  },
  {
    id: "xl",
    name: "PT XL Axiata Tbk",
    shortName: "XL Axiata",
    code: "XL",
    tagline: "Mobile Convergence, Fiber Backbone & B2B Solutions",
    avatarBg: "rgba(168, 85, 247, 0.16)",
    avatarColor: "#c084fc",
    borderColor: "rgba(168, 85, 247, 0.35)",
    tier: "Dedicated SLA",
    systemsCount: 7,
  },
  {
    id: "pertamina",
    name: "Pertamina Digital Enterprise",
    shortName: "Pertamina",
    code: "PERT",
    tagline: "Industrial SCADA, Downstream Fuel IoT & Enterprise Cloud",
    avatarBg: "rgba(20, 184, 166, 0.16)",
    avatarColor: "#2dd4bf",
    borderColor: "rgba(20, 184, 166, 0.35)",
    tier: "Enterprise NOC",
    systemsCount: 5,
  },
];

export const CLIENT_PROJECTS: Record<string, ProjectHealthEntry[]> = {
  tritronik: projects.map((p) => ({ ...p, clientId: "tritronik" })),
  bni: [
    { name: "BNI Mobile", status: "Needs Attention", detail: "Latensi API auth 850ms", tone: "warning", clientId: "bni" },
    { name: "Switching ATM", status: "Healthy", detail: "Link leased-line normal", tone: "success", clientId: "bni" },
    { name: "OpenBanking", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success", clientId: "bni" },
    { name: "Core Banking", status: "Healthy", detail: "Replikasi sync aktif", tone: "success", clientId: "bni" },
    { name: "QRIS Settle", status: "Needs Attention", detail: "Antrian kliring pending", tone: "warning", clientId: "bni" },
    { name: "Card Mgmt", status: "Healthy", detail: "Cluster node operasional", tone: "success", clientId: "bni" },
    { name: "Fraud Shield", status: "Healthy", detail: "AI scoring nominal", tone: "success", clientId: "bni" },
  ],
  telkomsel: [
    { name: "MyTelkomsel", status: "Healthy", detail: "Traffic stabil nominal", tone: "success", clientId: "telkomsel" },
    { name: "OCS Billing", status: "Needs Attention", detail: "Diameter link warning", tone: "warning", clientId: "telkomsel" },
    { name: "VAS Gateway", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success", clientId: "telkomsel" },
    { name: "5G Edge", status: "Healthy", detail: "Cluster pod normal", tone: "success", clientId: "telkomsel" },
    { name: "SMSC Core", status: "Healthy", detail: "Throughput 18k TPS", tone: "success", clientId: "telkomsel" },
    { name: "USSD *363#", status: "Needs Attention", detail: "Backlog sesi subuh", tone: "warning", clientId: "telkomsel" },
    { name: "HLR/HSS", status: "Healthy", detail: "Replikasi subscriber aktif", tone: "success", clientId: "telkomsel" },
  ],
  mandiri: [
    { name: "Livin' Superapp", status: "Healthy", detail: "Traffic stabil 24k TPS", tone: "success", clientId: "mandiri" },
    { name: "Wholesale Kopra", status: "Healthy", detail: "Corporate cash pool normal", tone: "success", clientId: "mandiri" },
    { name: "Mandiri Switcher", status: "Needs Attention", detail: "Switching interbank latency 620ms", tone: "warning", clientId: "mandiri" },
    { name: "Core Micro", status: "Healthy", detail: "Sync ledger cabang aktif", tone: "success", clientId: "mandiri" },
    { name: "e-Money Server", status: "Healthy", detail: "NFC update balance nominal", tone: "success", clientId: "mandiri" },
    { name: "BI-FAST Mandiri", status: "Healthy", detail: "Direct settlement lulus", tone: "success", clientId: "mandiri" },
  ],
  bca: [
    { name: "myBCA", status: "Healthy", detail: "API auth normal 180ms", tone: "success", clientId: "bca" },
    { name: "BCA Mobile", status: "Healthy", detail: "Load balancer normal", tone: "success", clientId: "bca" },
    { name: "Switching Kliring", status: "Healthy", detail: "Antrian pesan 0", tone: "success", clientId: "bca" },
    { name: "Halo BCA VoIP", status: "Healthy", detail: "Call center SIP trunk aktif", tone: "success", clientId: "bca" },
    { name: "Virtual Account", status: "Healthy", detail: "Replikasi real-time", tone: "success", clientId: "bca" },
    { name: "Merchant Settle", status: "Healthy", detail: "Batch settlement siap", tone: "success", clientId: "bca" },
  ],
  indosat: [
    { name: "IM3 Network", status: "Healthy", detail: "Throughput paket stabil", tone: "success", clientId: "indosat" },
    { name: "Core 4G/5G", status: "Needs Attention", detail: "MME overload Jawa Tengah", tone: "warning", clientId: "indosat" },
    { name: "Tri Gateway", status: "Healthy", detail: "Packet data routing normal", tone: "success", clientId: "indosat" },
    { name: "VAS Messaging", status: "Healthy", detail: "OTP delivery 99.8%", tone: "success", clientId: "indosat" },
    { name: "Billing Matrix", status: "Needs Attention", detail: "CDR parsing delayed 15m", tone: "warning", clientId: "indosat" },
  ],
  xl: [
    { name: "myXL", status: "Healthy", detail: "API service nominal", tone: "success", clientId: "xl" },
    { name: "AXIS Net", status: "Healthy", detail: "Voucher redeem normal", tone: "success", clientId: "xl" },
    { name: "XL Satu Fiber", status: "Needs Attention", detail: "GPON OLT warning regional 2", tone: "warning", clientId: "xl" },
    { name: "Core B2B", status: "Healthy", detail: "VPN enterprise normal", tone: "success", clientId: "xl" },
    { name: "Transport DWDM", status: "Healthy", detail: "Link optik 100G aktif", tone: "success", clientId: "xl" },
  ],
  pertamina: [
    { name: "MyPertamina", status: "Healthy", detail: "Subsidi tepat QR scanner normal", tone: "success", clientId: "pertamina" },
    { name: "Fuel SCADA", status: "Healthy", detail: "Telemetry tangki terminal normal", tone: "success", clientId: "pertamina" },
    { name: "LPG API", status: "Healthy", detail: "Integrasi sub-penyalur normal", tone: "success", clientId: "pertamina" },
    { name: "Subholding Cloud", status: "Healthy", detail: "Cluster hybrid cloud aman", tone: "success", clientId: "pertamina" },
  ],
};

export const CLIENT_SYSTEMS: Record<string, readonly string[]> = {
  tritronik: ["SM", "B2B", "USIEM", "MB", "EPC", "DM", "UNEM"],
  bni: ["BNI Mobile", "Switching ATM", "OpenBanking", "Core Banking", "QRIS Settle", "Card Mgmt", "Fraud Shield"],
  telkomsel: ["MyTelkomsel", "OCS Billing", "VAS Gateway", "5G Edge", "SMSC Core", "USSD *363#", "HLR/HSS"],
  mandiri: ["Livin'", "Wholesale Kopra", "Mandiri Switcher", "Core Micro", "e-Money", "BI-FAST"],
  bca: ["myBCA", "BCA Mobile", "Switching Kliring", "Halo BCA", "Virtual Account", "Merchant Settle"],
  indosat: ["IM3 Network", "Core 4G/5G", "Tri Gateway", "VAS Messaging", "Billing Matrix"],
  xl: ["myXL", "AXIS Net", "XL Satu", "Core B2B", "Transport DWDM"],
  pertamina: ["MyPertamina", "Fuel SCADA", "LPG API", "Subholding Cloud"],
};

export const CLIENT_SCHEDULES: Record<string, MonitoringEntry[]> = {
  tritronik: monitoringSchedule.map((m) => ({ ...m, clientId: "tritronik" })),
  bni: [
    { time: "13:00", project: "OpenBanking", task: "Gateway API & token auth TPS", owner: "Mhd. Galih Khairi", state: "Done", tone: "success", clientId: "bni" },
    { time: "14:00", project: "Switching ATM", task: "Health-check leased-line link ATM", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "bni" },
    { time: "15:00", project: "QRIS Settle", task: "Antrian pesan settlement kliring", owner: "Kristina Marbun", state: "Needs Attention", tone: "warning", clientId: "bni" },
    { time: "16:00", project: "Fraud Shield", task: "Score anomali transaksi mencurigakan", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", clientId: "bni" },
    { time: "17:00", project: "BNI Mobile", task: "Latency login & biometrik user", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", clientId: "bni" },
    { time: "18:00", project: "Card Mgmt", task: "Sinkronisasi bin-range kartu kredit", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", clientId: "bni" },
    { time: "19:00", project: "Core Banking", task: "Pre-EOD readiness & thread pool", owner: "Agnes", state: "Done", tone: "success", clientId: "bni" },
    { time: "20:00", project: "OpenBanking", task: "Rate limit partner fintech tier-1", owner: "Agnes", state: "Done", tone: "success", clientId: "bni" },
    { time: "21:00", project: "BNI Mobile", task: "Throughput transfer BI-FAST", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "bni" },
    { time: "21:00", project: "QRIS Settle", task: "Validasi batch settlement malam", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", overview: true, clientId: "bni" },
    { time: "22:00", project: "Switching ATM", task: "Jaringan switch antar-bank", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "bni" },
    { time: "22:00", project: "Core Banking", task: "Batch balancing ledger cabang", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "bni" },
    { time: "23:00", project: "Handover", task: "Kesiapan shift malam EOD BNI", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "bni" },
  ],
  telkomsel: [
    { time: "13:00", project: "MyTelkomsel", task: "Response time katalog paket data", owner: "Mhd. Galih Khairi", state: "Done", tone: "success", clientId: "telkomsel" },
    { time: "14:00", project: "5G Edge", task: "Utilisasi UPF gateway regional Jawa", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "telkomsel" },
    { time: "15:00", project: "VAS Gateway", task: "Queue SMS broadcast notifikasi", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "telkomsel" },
    { time: "16:00", project: "SMSC Core", task: "Throughput routing MT/MO SMS", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", clientId: "telkomsel" },
    { time: "17:00", project: "OCS Billing", task: "Diameter session charging round-trip", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", clientId: "telkomsel" },
    { time: "18:00", project: "USSD *363#", task: "Backlog sesi menu interaktif USSD", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", clientId: "telkomsel" },
    { time: "19:00", project: "HLR/HSS", task: "Replikasi subscriber database node 04", owner: "Agnes", state: "Done", tone: "success", clientId: "telkomsel" },
    { time: "20:00", project: "MyTelkomsel", task: "Payment gateway voucher e-wallet", owner: "Agnes", state: "Done", tone: "success", clientId: "telkomsel" },
    { time: "21:00", project: "5G Edge", task: "Latency control-plane gNodeB", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "telkomsel" },
    { time: "21:00", project: "OCS Billing", task: "Kapasitas throttle CDR real-time", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", overview: true, clientId: "telkomsel" },
    { time: "22:00", project: "USSD *363#", task: "Validasi load peak hour malam", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "telkomsel" },
    { time: "22:00", project: "SMSC Core", task: "Audit antrian OTP banking via SMS", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "telkomsel" },
    { time: "23:00", project: "Handover", task: "Tinjauan shift malam Telkomsel", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "telkomsel" },
  ],
  mandiri: [
    { time: "13:00", project: "Livin' Superapp", task: "API Gateway token auth TPS", owner: "Mhd. Galih Khairi", state: "Done", tone: "success", clientId: "mandiri" },
    { time: "14:00", project: "Wholesale Kopra", task: "Corporate cash pool validation", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "mandiri" },
    { time: "16:00", project: "Mandiri Switcher", task: "Interbank switching latency check", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", clientId: "mandiri" },
    { time: "18:00", project: "Core Micro", task: "Sync ledger cabang micro", owner: "Agnes", state: "Done", tone: "success", clientId: "mandiri" },
    { time: "20:00", project: "e-Money Server", task: "NFC update balance gateway", owner: "Agnes", state: "Done", tone: "success", clientId: "mandiri" },
    { time: "22:00", project: "BI-FAST Mandiri", task: "Direct settlement clearing queue", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "mandiri" },
    { time: "23:00", project: "Handover", task: "Handover shift malam Mandiri", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "mandiri" },
  ],
  bca: [
    { time: "13:00", project: "myBCA", task: "Single identity OAuth verification", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "bca" },
    { time: "15:00", project: "BCA Mobile", task: "Load balancer health cluster 01", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "bca" },
    { time: "17:00", project: "Switching Kliring", task: "Switching queue RTGS & SKN", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", clientId: "bca" },
    { time: "19:00", project: "Virtual Account", task: "Real-time payment callback sync", owner: "Agnes", state: "Done", tone: "success", clientId: "bca" },
    { time: "21:00", project: "Merchant Settle", task: "EDC & QRIS batch balancing", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "bca" },
    { time: "23:00", project: "Handover", task: "Handover shift malam BCA", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "bca" },
  ],
  indosat: [
    { time: "13:00", project: "IM3 Network", task: "User plane throughput packet drop", owner: "Mhd. Galih Khairi", state: "Done", tone: "success", clientId: "indosat" },
    { time: "15:00", project: "Core 4G/5G", task: "MME connection pool regional Jawa", owner: "Kristina Marbun", state: "Needs Attention", tone: "warning", clientId: "indosat" },
    { time: "17:00", project: "Tri Gateway", task: "Data session authentication HLR", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", clientId: "indosat" },
    { time: "19:00", project: "Billing Matrix", task: "Mediation CDR stream parsing", owner: "Agnes", state: "Needs Attention", tone: "warning", clientId: "indosat" },
    { time: "21:00", project: "VAS Messaging", task: "OTP banking SMS throughput", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "indosat" },
    { time: "23:00", project: "Handover", task: "Tinjauan shift malam Indosat", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "indosat" },
  ],
  xl: [
    { time: "13:00", project: "myXL", task: "Self-service API response time", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "xl" },
    { time: "15:00", project: "AXIS Net", task: "Digital bonus redemption traffic", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "xl" },
    { time: "17:00", project: "XL Satu Fiber", task: "GPON OLT uplink telemetry", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", clientId: "xl" },
    { time: "19:00", project: "Core B2B", task: "MPLS VPN leased-line latency", owner: "Agnes", state: "Done", tone: "success", clientId: "xl" },
    { time: "21:00", project: "Transport DWDM", task: "Optical backbone link utilization", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true, clientId: "xl" },
    { time: "23:00", project: "Handover", task: "Shift malam EOD check", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "xl" },
  ],
  pertamina: [
    { time: "14:00", project: "MyPertamina", task: "Subsidi tepat QR scanner latency", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "pertamina" },
    { time: "16:00", project: "Fuel SCADA", task: "Terminal fuel level telemetry sensor", owner: "Kristina Marbun", state: "Done", tone: "success", clientId: "pertamina" },
    { time: "18:00", project: "LPG API", task: "Quota distribution agent sync", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", clientId: "pertamina" },
    { time: "21:00", project: "Subholding Cloud", task: "Hybrid cloud container health", owner: "Agnes", state: "Done", tone: "success", overview: true, clientId: "pertamina" },
    { time: "23:00", project: "Handover", task: "Handover shift malam Pertamina", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true, clientId: "pertamina" },
  ],
};

export const SEED_BNI_TICKETS: Ticket[] = [
  {
    id: "bni-86d401",
    subject: "[BNI Mobile] Lonjakan latensi autentikasi biometrik",
    project: "BNI Mobile",
    severity: "High",
    type: "Incident",
    category: "Incident",
    owner: "Kristina Marbun",
    status: "Active",
    created: "20:15",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 1.2,
    responseMinutes: 8,
    slaTargetMinutes: 60,
    clientId: "bni",
    description: "Pelanggan mengalami response time lambat (> 2000ms) saat verifikasi sidik jari/face-ID di aplikasi BNI Mobile.",
    history: [
      { time: "20:15", action: "Ticket dibuat otomatis dari Dynatrace alert threshold latensi biometrik.", author: "System APM", type: "created" },
      { time: "20:25", action: "Tim melakukan scale-out pod microservice auth cluster 02.", author: "Kristina Marbun", type: "response" },
    ],
  },
  {
    id: "bni-86d402",
    subject: "[QRIS Settle] Penumpukan antrian transaksi kliring merchant",
    project: "QRIS Settle",
    severity: "Critical",
    type: "Incident",
    category: "Incident",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "19:40",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 2.1,
    responseMinutes: 5,
    slaTargetMinutes: 60,
    clientId: "bni",
    description: "Antrian batch settlement QRIS pedagang mengalami lag di Kafka topic qris-clearing. 450 transaksi tertahan.",
    history: [
      { time: "19:40", action: "Ticket incident dibuat setelah consumer group lag melampaui 10.000 pesan.", author: "M. Ihsanul Arifin", type: "created" },
      { time: "19:55", action: "Pembersihan thread pool broker kliring sedang berlangsung.", author: "M. Ihsanul Arifin", type: "response" },
    ],
  },
  {
    id: "bni-86d403",
    subject: "[Switching ATM] Fluktuasi koneksi leased-line cabang regional 03",
    project: "Switching ATM",
    severity: "Medium",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Mhd. Galih Khairi",
    owners: ["Mhd. Galih Khairi", "Kristina Marbun"],
    requestTime: "18:00",
    responseTime: "18:15",
    isStillOpen: true,
    status: "Pending",
    created: "18:00",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 3.5,
    responseMinutes: 15,
    slaTargetMinutes: 120,
    clientId: "bni",
    description: "Pemeriksaan packet loss pada jalur router ATM interkoneksi regional 03 bersama vendor telekomunikasi.",
    history: [
      { time: "18:00", action: "Permintaan validasi link switch ATM dibuat.", author: "Mhd. Galih Khairi", type: "created" },
    ],
  },
  {
    id: "bni-86d404",
    subject: "[Core Banking] Pemeliharaan indeks basis data EOD batch malam",
    project: "Core Banking",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Agnes",
    status: "Closed",
    created: "17:00",
    date: "2026-08-31",
    shift: "Pagi",
    agingHours: 4.5,
    responseMinutes: 10,
    resolutionMinutes: 45,
    slaTargetMinutes: 120,
    clientId: "bni",
    description: "Re-indexing tabel transaksi ledger harian untuk persiapan pergantian buku akhir bulan.",
    history: [
      { time: "17:00", action: "Change request disetujui dan dieksekusi.", author: "Agnes", type: "created" },
      { time: "17:45", action: "Re-indexing selesai tanpa kendala. Tiket ditutup.", author: "Agnes", type: "status_change" },
    ],
  },
  {
    id: "bni-86d405",
    subject: "[OpenBanking] Permintaan whitelist IP gateway partner fintech",
    project: "OpenBanking",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "14:30",
    date: "2026-08-31",
    shift: "Pagi",
    agingHours: 7.0,
    responseMinutes: 12,
    resolutionMinutes: 28,
    slaTargetMinutes: 120,
    clientId: "bni",
    description: "Pendaftaran CIDR subnet partner pembayaran digital pada WAF dan security group OpenBanking API.",
    history: [
      { time: "14:30", action: "Tiket dibuat.", author: "Pangondion Kurniawan", type: "created" },
      { time: "14:58", action: "Konfigurasi WAF divalidasi. Tiket ditutup.", author: "Pangondion Kurniawan", type: "status_change" },
    ],
  },
  {
    id: "bni-86d406",
    subject: "[Fraud Shield] Anomali transaksi multi-kartu di terminal luar negeri",
    project: "Fraud Shield",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "21:10",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 0.5,
    responseMinutes: 4,
    slaTargetMinutes: 60,
    clientId: "bni",
    description: "Deteksi lonjakan percobaan otorisasi CVV dari BIN kartu BNI di gateway pembayaran internasional.",
    history: [
      { time: "21:10", action: "Eskalasi ke unit Card Security & Anti-Fraud NOC BNI.", author: "M. Ihsanul Arifin", type: "created" },
    ],
  },
];

export const SEED_TELKOMSEL_TICKETS: Ticket[] = [
  {
    id: "tsel-86d401",
    subject: "[OCS Billing] Latency spike pada Diameter session charging OCS",
    project: "OCS Billing",
    severity: "Critical",
    type: "Incident",
    category: "Incident",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "19:15",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 2.3,
    responseMinutes: 5,
    slaTargetMinutes: 60,
    clientId: "telkomsel",
    description: "Waktu respons Diameter CCR/CCA melampaui 450ms. Berdampak pada delay pemotongan pulsa/kuota paket data realtime.",
    history: [
      { time: "19:15", action: "Alert Diameter OCS terdeteksi.", author: "M. Ihsanul Arifin", type: "created" },
      { time: "19:30", action: "Koordinasi dengan tim Core Network Telkomsel untuk bypass rute pool 03.", author: "M. Ihsanul Arifin", type: "response" },
    ],
  },
  {
    id: "tsel-86d402",
    subject: "[USSD *363#] Antrian request USSD melebihi batas toleransi 5k TPS",
    project: "USSD *363#",
    severity: "High",
    type: "Incident",
    category: "Incident",
    owner: "Kristina Marbun",
    status: "Active",
    created: "20:00",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 1.5,
    responseMinutes: 6,
    slaTargetMinutes: 60,
    clientId: "telkomsel",
    description: "Lonjakan akses pelanggan pada menu promo internet *363# menyebabkan timeout di layer HLR gateway.",
    history: [
      { time: "20:00", action: "Tiket dibuat.", author: "Kristina Marbun", type: "created" },
    ],
  },
  {
    id: "tsel-86d403",
    subject: "[5G Edge] Penyesuaian bandwidth rute regional Java-Bali",
    project: "5G Edge",
    severity: "Medium",
    type: "Change Request",
    category: "Change Request",
    owner: "Mhd. Galih Khairi",
    status: "Pending",
    created: "18:20",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 3.1,
    responseMinutes: 14,
    slaTargetMinutes: 120,
    clientId: "telkomsel",
    description: "Penambahan alokasi slice UPF 5G untuk persiapan event konser internasional di area Denpasar.",
    history: [
      { time: "18:20", action: "Change request dibuat.", author: "Mhd. Galih Khairi", type: "created" },
    ],
  },
  {
    id: "tsel-86d404",
    subject: "[MyTelkomsel] Verifikasi integrasi payment channel QRIS & e-Wallet",
    project: "MyTelkomsel",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Agnes",
    status: "Closed",
    created: "15:00",
    date: "2026-08-31",
    shift: "Pagi",
    agingHours: 6.5,
    responseMinutes: 10,
    resolutionMinutes: 35,
    slaTargetMinutes: 120,
    clientId: "telkomsel",
    description: "Pengujian end-to-end transaksi pembelian kuota internet menggunakan metode QRIS di aplikasi versi beta.",
    history: [
      { time: "15:00", action: "Permintaan validasi dibuat.", author: "Agnes", type: "created" },
      { time: "15:35", action: "Pengujian 10/10 transaksi sukses. Tiket ditutup.", author: "Agnes", type: "status_change" },
    ],
  },
  {
    id: "tsel-86d405",
    subject: "[SMSC Core] Normalisasi queue pengiriman SMS OTP bank partner",
    project: "SMSC Core",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "13:10",
    date: "2026-08-31",
    shift: "Pagi",
    agingHours: 8.0,
    responseMinutes: 5,
    resolutionMinutes: 40,
    slaTargetMinutes: 60,
    clientId: "telkomsel",
    description: "SMSC node Jakarta Timur sempat mengalami backlog buffer 12.000 SMS akibat gangguan routing interkoneksi.",
    history: [
      { time: "13:10", action: "Eskalasi ke engineer SMSC Telkomsel.", author: "Pangondion Kurniawan", type: "created" },
      { time: "13:50", action: "Buffer telah normal, delivery rate 99.8%. Tiket ditutup.", author: "Pangondion Kurniawan", type: "status_change" },
    ],
  },
  {
    id: "tsel-86d406",
    subject: "[HLR/HSS] Pemeriksaan replikasi data subscriber node cluster 05",
    project: "HLR/HSS",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "11:00",
    date: "2026-08-31",
    shift: "Subuh",
    agingHours: 10.5,
    responseMinutes: 15,
    resolutionMinutes: 50,
    slaTargetMinutes: 120,
    clientId: "telkomsel",
    description: "Audit periodik sinkronisasi profil pelanggan pascabayar antara node aktif dan standby.",
    history: [
      { time: "11:00", action: "Maintenance rutin dijalankan.", author: "M. Ihsanul Arifin", type: "created" },
      { time: "11:50", action: "Semua checksum identik. Tiket ditutup.", author: "M. Ihsanul Arifin", type: "status_change" },
    ],
  },
];

export const SEED_BNI_ASSESSMENTS: HistoricalAssessmentEntry[] = [
  { id: "bni-h-01", date: "2026-08-31", time: "13:00", project: "OpenBanking", task: "Gateway API & token auth TPS", owner: "Mhd. Galih Khairi", verdict: "ok", note: "API gateway normal, error rate 0.02%", clientId: "bni" },
  { id: "bni-h-02", date: "2026-08-31", time: "14:00", project: "Switching ATM", task: "Health-check leased-line link ATM", owner: "Kristina Marbun", verdict: "ok", note: "Uptime leased line 100%", clientId: "bni" },
  { id: "bni-h-03", date: "2026-08-31", time: "15:00", project: "QRIS Settle", task: "Antrian pesan settlement kliring", owner: "Kristina Marbun", verdict: "nok", note: "Lag 450 transaksi di Kafka kliring", clientId: "bni" },
  { id: "bni-h-04", date: "2026-08-31", time: "16:00", project: "Fraud Shield", task: "Score anomali transaksi mencurigakan", owner: "M. Ihsanul Arifin", verdict: "ok", note: "AI anomaly threshold aman", clientId: "bni" },
  { id: "bni-h-05", date: "2026-08-31", time: "17:00", project: "BNI Mobile", task: "Latency login & biometrik user", owner: "M. Ihsanul Arifin", verdict: "nok", note: "Response time biometrik 850ms", clientId: "bni" },
  { id: "bni-h-06", date: "2026-08-31", time: "18:00", project: "Card Mgmt", task: "Sinkronisasi bin-range kartu kredit", owner: "M. Ihsanul Arifin", verdict: "ok", note: "Replika in sync", clientId: "bni" },
  { id: "bni-h-07", date: "2026-08-31", time: "19:00", project: "Core Banking", task: "Pre-EOD readiness & thread pool", owner: "Agnes", verdict: "ok", note: "Thread pool tersedia 80%", clientId: "bni" },
  { id: "bni-h-08", date: "2026-08-31", time: "20:00", project: "OpenBanking", task: "Rate limit partner fintech tier-1", owner: "Agnes", verdict: "ok", note: "Quota limit normal", clientId: "bni" },
];

export const SEED_TELKOMSEL_ASSESSMENTS: HistoricalAssessmentEntry[] = [
  { id: "tsel-h-01", date: "2026-08-31", time: "13:00", project: "MyTelkomsel", task: "Response time katalog paket data", owner: "Mhd. Galih Khairi", verdict: "ok", note: "Catalog load time 420ms normal", clientId: "telkomsel" },
  { id: "tsel-h-02", date: "2026-08-31", time: "14:00", project: "5G Edge", task: "Utilisasi UPF gateway regional Jawa", owner: "Kristina Marbun", verdict: "ok", note: "Throughput 6.2 Gbps stabil", clientId: "telkomsel" },
  { id: "tsel-h-03", date: "2026-08-31", time: "15:00", project: "VAS Gateway", task: "Queue SMS broadcast notifikasi", owner: "Kristina Marbun", verdict: "ok", note: "Antrian bersih < 100 pesan", clientId: "telkomsel" },
  { id: "tsel-h-04", date: "2026-08-31", time: "16:00", project: "SMSC Core", task: "Throughput routing MT/MO SMS", owner: "M. Ihsanul Arifin", verdict: "ok", note: "Rata-rata 18.200 TPS", clientId: "telkomsel" },
  { id: "tsel-h-05", date: "2026-08-31", time: "17:00", project: "OCS Billing", task: "Diameter session charging round-trip", owner: "M. Ihsanul Arifin", verdict: "nok", note: "Diameter CCR round-trip 450ms", clientId: "telkomsel" },
  { id: "tsel-h-06", date: "2026-08-31", time: "18:00", project: "USSD *363#", task: "Backlog sesi menu interaktif USSD", owner: "M. Ihsanul Arifin", verdict: "nok", note: "Backlog 5.2k sesi di HLR gateway", clientId: "telkomsel" },
  { id: "tsel-h-07", date: "2026-08-31", time: "19:00", project: "HLR/HSS", task: "Replikasi subscriber database node 04", owner: "Agnes", verdict: "ok", note: "Sync lag < 1s", clientId: "telkomsel" },
  { id: "tsel-h-08", date: "2026-08-31", time: "20:00", project: "MyTelkomsel", task: "Payment gateway voucher e-wallet", owner: "Agnes", verdict: "ok", note: "Payment callback 99.9%", clientId: "telkomsel" },
];

export const SEED_EXTENDED_CLIENT_TICKETS: Ticket[] = [
  {
    id: "bmri-86d401",
    subject: "[Mandiri Switcher] Interbank switching latency warning",
    project: "Mandiri Switcher",
    severity: "Medium",
    type: "Incident",
    category: "Incident",
    owner: "Kristina Marbun",
    status: "Active",
    created: "19:40",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 1.5,
    responseMinutes: 10,
    slaTargetMinutes: 60,
    clientId: "mandiri",
    description: "Latensi interbank switching naik menyentuh 620ms pada jam transaksi malam.",
    history: [{ time: "19:40", action: "Ticket dibuat.", author: "Kristina Marbun", type: "created" }],
  },
  {
    id: "bca-86d401",
    subject: "[myBCA] Audit performa OAuth gateway pasca-deploy",
    project: "myBCA",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Agnes",
    status: "Closed",
    created: "14:15",
    date: "2026-08-31",
    shift: "Pagi",
    agingHours: 7.0,
    responseMinutes: 8,
    slaTargetMinutes: 120,
    clientId: "bca",
    description: "Validasi response time auth OAuth di bawah 200ms.",
    history: [{ time: "14:15", action: "Ticket dibuat.", author: "Agnes", type: "created" }],
  },
  {
    id: "isat-86d401",
    subject: "[Core 4G/5G] MME load imbalance region Jawa Tengah",
    project: "Core 4G/5G",
    severity: "Critical",
    type: "Incident",
    category: "Incident",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "20:30",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 0.8,
    responseMinutes: 5,
    slaTargetMinutes: 30,
    clientId: "indosat",
    description: "MME cluster node 02 mencapai 92% capacity load.",
    history: [{ time: "20:30", action: "Ticket dibuat.", author: "M. Ihsanul Arifin", type: "created" }],
  },
  {
    id: "xl-86d401",
    subject: "[XL Satu Fiber] GPON OLT uplink telemetry warning",
    project: "XL Satu Fiber",
    severity: "Medium",
    type: "Incident",
    category: "Incident",
    owner: "Mhd. Galih Khairi",
    status: "Active",
    created: "21:05",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 0.4,
    responseMinutes: 12,
    slaTargetMinutes: 60,
    clientId: "xl",
    description: "Uplink packet drop pada OLT regional 2.",
    history: [{ time: "21:05", action: "Ticket dibuat.", author: "Mhd. Galih Khairi", type: "created" }],
  },
  {
    id: "pert-86d401",
    subject: "[Fuel SCADA] Telemetry sync interval calibration",
    project: "Fuel SCADA",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "16:20",
    date: "2026-08-31",
    shift: "Pagi",
    agingHours: 5.0,
    responseMinutes: 15,
    slaTargetMinutes: 120,
    clientId: "pertamina",
    description: "Kalibrasi interval sync sensor tangki bahan bakar minyak.",
    history: [{ time: "16:20", action: "Ticket dibuat.", author: "Agnes", type: "created" }],
  },
];

export const ALL_COMBINED_SEED_TICKETS: Ticket[] = [
  ...seedTickets.map((t) => ({ ...t, clientId: t.clientId || "tritronik" })),
  ...SEED_BNI_TICKETS,
  ...SEED_TELKOMSEL_TICKETS,
  ...SEED_EXTENDED_CLIENT_TICKETS,
];

// ── Client-Scoped Query Helpers ──

export function getClientProjects(clientId?: string): ProjectHealthEntry[] {
  const cid = (clientId || "tritronik").toLowerCase();
  return CLIENT_PROJECTS[cid] || CLIENT_PROJECTS.tritronik;
}

export function getClientSystems(clientId?: string): readonly string[] {
  const cid = (clientId || "tritronik").toLowerCase();
  return CLIENT_SYSTEMS[cid] || CLIENT_SYSTEMS.tritronik;
}

export function getClientMonitoringSchedule(clientId?: string): MonitoringEntry[] {
  const cid = (clientId || "tritronik").toLowerCase();
  return CLIENT_SCHEDULES[cid] || CLIENT_SCHEDULES.tritronik;
}

export function getClientHistoricalAssessments(clientId?: string): HistoricalAssessmentEntry[] {
  const cid = (clientId || "tritronik").toLowerCase();
  if (cid === "bni") return SEED_BNI_ASSESSMENTS;
  if (cid === "telkomsel") return SEED_TELKOMSEL_ASSESSMENTS;
  return seedHistoricalAssessments.map((a) => ({ ...a, clientId: "tritronik" }));
}

export function getClientTickets(allTickets: Ticket[], clientId?: string): Ticket[] {
  const cid = (clientId || "tritronik").toLowerCase();
  return allTickets.filter((t) => {
    const tCid = (t.clientId || "tritronik").toLowerCase();
    return tCid === cid;
  });
}

export const CLIENT_HANDOVER_TASKS: Record<string, HandoverTask[]> = {
  tritronik: initialHandoverTasks,
  bni: [
    {
      id: 101,
      taskTemplateId: "bni-std-1",
      isNewlyAdded: false,
      title: "Validasi token rotation partner fintech",
      project: "OpenBanking",
      detail: "Pemeriksaan token OAuth2 expired & rate limiter partner fintech tier-1.",
      state: "repeat",
      completed: true,
    },
    {
      id: 102,
      taskTemplateId: "bni-std-2",
      isNewlyAdded: false,
      title: "Health-check leased-line link ATM switching",
      project: "Switching ATM",
      detail: "Pastikan uptime leased line 100% dan tidak ada packet loss antar-node.",
      state: "repeat",
      completed: true,
    },
    {
      id: 103,
      taskTemplateId: "bni-std-3",
      isNewlyAdded: false,
      title: "Monitoring queue settlement kliring BI-FAST",
      project: "QRIS Settle",
      detail: "Pantau antrian pesan kliring BI-FAST dan Kafka cluster settlement.",
      state: "repeat",
      completed: true,
    },
    {
      id: 104,
      taskTemplateId: "bni-std-4",
      isNewlyAdded: false,
      title: "Sinkronisasi bin-range kartu kredit",
      project: "Card Mgmt",
      detail: "Validasi replikasi bin-range database antar cluster aktif dan standby.",
      state: "repeat",
      completed: true,
    },
    {
      id: 105,
      taskTemplateId: "bni-std-5",
      isNewlyAdded: false,
      title: "Pre-EOD readiness & thread pool check",
      project: "Core Banking",
      detail: "Verifikasi kapasitas thread pool database core banking menjelang batch EOD malam.",
      state: "repeat",
      completed: true,
    },
    {
      id: 106,
      taskTemplateId: "bni-std-6",
      isNewlyAdded: false,
      title: "Review false-positive alert AI transaksi anomali",
      project: "Fraud Shield",
      detail: "Periksa transaksi bernilai besar yang ter-flag scoring anomali.",
      state: "repeat",
      completed: true,
    },
    {
      id: 107,
      taskTemplateId: "bni-std-7",
      isNewlyAdded: true,
      title: "Investigasi lonjakan latensi autentikasi biometrik",
      project: "BNI Mobile",
      detail: "Koordinasi dengan DevOps untuk scale-out auth pod cluster 02.",
      state: "in-progress",
      completed: false,
    },
    {
      id: 108,
      taskTemplateId: "bni-std-8",
      isNewlyAdded: true,
      title: "Rekonsiliasi batch balancing ledger cabang",
      project: "Core Banking",
      detail: "Monitoring penyelesaian balancing ledger sebelum cut-off jam 23:00.",
      state: "waiting",
      completed: false,
    },
  ],
  telkomsel: [
    {
      id: 201,
      taskTemplateId: "tsel-std-1",
      isNewlyAdded: false,
      title: "Health-check response time katalog paket data",
      project: "MyTelkomsel",
      detail: "Pantau response time API gateway katalog agar tetap stabil di bawah 450ms.",
      state: "repeat",
      completed: true,
    },
    {
      id: 202,
      taskTemplateId: "tsel-std-2",
      isNewlyAdded: false,
      title: "Monitoring throughput UPF gateway 5G regional Jawa",
      project: "5G Edge",
      detail: "Pastikan throughput data user plane stabil tanpa lonjakan packet drop.",
      state: "repeat",
      completed: true,
    },
    {
      id: 203,
      taskTemplateId: "tsel-std-3",
      isNewlyAdded: false,
      title: "Verifikasi queue SMS broadcast notifikasi",
      project: "VAS Gateway",
      detail: "Pastikan antrian SMS broadcast promo dan informasi pelanggan < 100 antrian.",
      state: "repeat",
      completed: true,
    },
    {
      id: 204,
      taskTemplateId: "tsel-std-4",
      isNewlyAdded: false,
      title: "Audit delivery rate MT/MO dan OTP perbankan",
      project: "SMSC Core",
      detail: "Pastikan delivery rate SMS OTP perbankan tetap di atas 99.8%.",
      state: "repeat",
      completed: true,
    },
    {
      id: 205,
      taskTemplateId: "tsel-std-5",
      isNewlyAdded: false,
      title: "Pemeriksaan sinkronisasi subscriber database node 04",
      project: "HLR/HSS",
      detail: "Audit delay replikasi profil pelanggan antar node aktif dan standby.",
      state: "repeat",
      completed: true,
    },
    {
      id: 206,
      taskTemplateId: "tsel-std-6",
      isNewlyAdded: false,
      title: "Monitoring latency control-plane gNodeB",
      project: "5G Edge",
      detail: "Pantau latency sinyal kontrol radio gNodeB area urban.",
      state: "repeat",
      completed: true,
    },
    {
      id: 207,
      taskTemplateId: "tsel-std-7",
      isNewlyAdded: false,
      title: "Rekap throughput CDR real-time",
      project: "OCS Billing",
      detail: "Validasi kelancaran pemrosesan CDR charging panggilan dan data.",
      state: "repeat",
      completed: true,
    },
    {
      id: 208,
      taskTemplateId: "tsel-std-8",
      isNewlyAdded: true,
      title: "Penyelidikan latency Diameter session charging",
      project: "OCS Billing",
      detail: "Investigasi round-trip time Diameter CCR yang sempat menyentuh 450ms.",
      state: "in-progress",
      completed: false,
    },
    {
      id: 209,
      taskTemplateId: "tsel-std-9",
      isNewlyAdded: true,
      title: "Mitigasi backlog sesi menu interaktif USSD",
      project: "USSD *363#",
      detail: "Pembersihan buffer sesi menggantung pada gateway USSD subuh.",
      state: "waiting",
      completed: false,
    },
  ],
};

export function getClientHandoverTasks(
  clientId?: string,
  activeRecordTasks?: HandoverTask[],
  activeClientId?: string
): HandoverTask[] {
  const cid = (clientId || "tritronik").toLowerCase();
  if (
    activeRecordTasks &&
    activeRecordTasks.length > 0 &&
    activeClientId &&
    activeClientId.toLowerCase() === cid
  ) {
    return activeRecordTasks;
  }
  return CLIENT_HANDOVER_TASKS[cid] || CLIENT_HANDOVER_TASKS.tritronik;
}

