import type {
  HandoverDraft,
  HandoverRecordData,
  HandoverTask,
  HistoricalAssessmentEntry,
  MonitoringEntry,
  ProjectHealthEntry,
  RosterMember,
  ShiftSwapRequest,
  Ticket,
} from "./types";
import { getNextShiftChange, getShiftInfo } from "./shifts";

export const projects: ProjectHealthEntry[] = [
  { name: "SM", status: "Needs Attention", detail: "1 pengecualian", tone: "warning" },
  { name: "B2B", status: "Needs Attention", detail: "Pemeriksaan Kafka", tone: "warning" },
  { name: "USIEM", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "MB", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "EPC", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "DM", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
  { name: "UNEM", status: "Healthy", detail: "Semua pemeriksaan lulus", tone: "success" },
];

export const attentionItems = [
  {
    project: "SM",
    title: "Queue ActiveMQ 228 memerlukan validasi",
    note: "Penumpukan queue dilaporkan pada checkpoint 18:00. Belum ada konfirmasi dari penanggung jawab.",
    time: "4 jam lalu",
    tone: "warning" as const,
    tag: "Queue",
  },
  {
    project: "B2B",
    title: "Aliran pesan tidak ada pada topik b2b-f…",
    note: "Terdeteksi saat validasi Kafka UI. Periksa kesehatan producer sebelum checkpoint berikutnya.",
    time: "4 jam lalu",
    tone: "warning" as const,
    tag: "Kafka",
  },
  {
    project: "EPC Tools",
    title: "Satu permintaan ad-hoc masih berlangsung",
    note: "Tinjau tugas approval entities sebelum handover shift.",
    time: "1 jam lalu",
    tone: "info" as const,
    tag: "Ticket",
  },
];

export const monitoringSchedule: MonitoringEntry[] = [
  { time: "13:00", project: "EPC Core", task: "Status layanan Catalog & Order", owner: "Mhd. Galih Khairi", state: "Done", tone: "success" },
  { time: "14:00", project: "APH", task: "Output Rate & Consumer Rate per PoP", owner: "Kristina Marbun", state: "Done", tone: "success" },
  { time: "15:00", project: "DM", task: "Device quota LintasArta", owner: "Kristina Marbun", state: "Done", tone: "success" },
  { time: "16:00", project: "UNEM", task: "Layanan & alert Grafana", owner: "M. Ihsanul Arifin", state: "Done", tone: "success" },
  { time: "17:00", project: "SM/ActiveMQ", task: "Queue fulldecode smng109", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning" },
  { time: "18:00", project: "B2B", task: "Disk usage /apps pv-bbsvsoe1", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning" },
  { time: "19:00", project: "USIEM", task: "Graylog input SIEM stream", owner: "Agnes", state: "Done", tone: "success" },
  { time: "20:00", project: "MB", task: "Push notification queue", owner: "Agnes", state: "Done", tone: "success" },
  { time: "21:00", project: "B2B", task: "Traffic topik Kafka", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", overview: true },
  { time: "21:00", project: "DM", task: "Utilisasi CPU Grafana", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "22:00", project: "SM", task: "Queue ActiveMQ 228 · 71 · 68", owner: "M. Ihsanul Arifin", state: "Needs Attention", tone: "warning", overview: true },
  { time: "22:00", project: "USIEM", task: "Graylog & Dashboard SIEM", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "22:00", project: "EPC Core", task: "Status layanan Catalog", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "22:00", project: "UNEM", task: "Layanan & alert Grafana", owner: "M. Ihsanul Arifin", state: "Done", tone: "success", overview: true },
  { time: "23:00", project: "Handover", task: "Tinjauan kesiapan shift malam", owner: "Shift malam", state: "Upcoming", tone: "neutral", overview: true },
];

export const monitoringSystems = ["ActiveMQ", "Kafka", "Grafana", "Graylog", "Disk Usage"] as const;

export const seedHistoricalAssessments: HistoricalAssessmentEntry[] = [
  // Today (2026-08-31)
  {
    id: "hist-31-1300",
    date: "2026-08-31",
    time: "13:00",
    project: "EPC Core",
    task: "Status layanan Catalog & Order",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Semua pod catalog berjalan normal, error rate 0.01%.",
  },
  {
    id: "hist-31-1400",
    date: "2026-08-31",
    time: "14:00",
    project: "APH",
    task: "Output Rate & Consumer Rate per PoP",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Traffic PoP 1-4 stabil rata-rata 12.4k req/sec.",
  },
  {
    id: "hist-31-1500",
    date: "2026-08-31",
    time: "15:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Sinkronisasi quota berjalan lancar, tidak ada perangkat over-limit.",
  },
  {
    id: "hist-31-1600",
    date: "2026-08-31",
    time: "16:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Dashboard Grafana sehat, latency P95 di bawah 120ms.",
  },
  {
    id: "hist-31-1700",
    date: "2026-08-31",
    time: "17:00",
    project: "SM/ActiveMQ",
    task: "Queue fulldecode smng109",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Queue fulldecode meningkat ke 4.800 pesan. Eskalasi ticket #86d40cxuk.",
  },
  {
    id: "hist-31-1800",
    date: "2026-08-31",
    time: "18:00",
    project: "B2B",
    task: "Disk usage /apps pv-bbsvsoe1",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Disk /apps mencapai 92.4%. Pembersihan temporary files dilakukan.",
  },
  {
    id: "hist-31-1900",
    date: "2026-08-31",
    time: "19:00",
    project: "USIEM",
    task: "Graylog input SIEM stream",
    owner: "Agnes",
    verdict: "ok",
    note: "Throughput Graylog 45.000 msg/s, buffer memory aman.",
  },
  {
    id: "hist-31-2000",
    date: "2026-08-31",
    time: "20:00",
    project: "MB",
    task: "Push notification queue",
    owner: "Agnes",
    verdict: "ok",
    note: "Queue push notification kosong, delivery rate 99.8%.",
  },
  // Yesterday (2026-08-30)
  {
    id: "hist-30-2200",
    date: "2026-08-30",
    time: "22:00",
    project: "EPC Core",
    task: "Memory Leak pada Catalog Service Pods",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Crashloop terdeteksi pada pod catalog, eskalasi L3 ticket #86d40esc2.",
  },
  {
    id: "hist-30-2100",
    date: "2026-08-30",
    time: "21:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Consumer lag normal di bawah 1.500 pesan.",
  },
  {
    id: "hist-30-1900",
    date: "2026-08-30",
    time: "19:00",
    project: "USIEM",
    task: "Graylog & Dashboard SIEM",
    owner: "Agnes",
    verdict: "ok",
    note: "Semua stream input SIEM aktif tanpa error rate.",
  },
  {
    id: "hist-30-1600",
    date: "2026-08-30",
    time: "16:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "Galih Khairi",
    verdict: "ok",
    note: "Cluster node utilization merata pada kisaran 65%.",
  },
  {
    id: "hist-30-1400",
    date: "2026-08-30",
    time: "14:00",
    project: "APH",
    task: "Rebalance Consumer Area 1 CGNAT",
    owner: "Pangondion Kurniawan",
    verdict: "nok",
    note: "Egress listener throttling pada Area 1, konfigurasi disesuaikan #86d40y02a.",
  },
  // 29 Aug 2026
  {
    id: "hist-29-2200",
    date: "2026-08-29",
    time: "22:00",
    project: "SM",
    task: "Queue ActiveMQ 228 · 71 · 68",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Queue fulldecode mencapai 3.200 pesan. Eskalasi dispatch.",
  },
  {
    id: "hist-29-2000",
    date: "2026-08-29",
    time: "20:00",
    project: "SM",
    task: "Queue ActiveMQ 228",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Kondisi queue normal, 120 pesan pending terproses.",
  },
  {
    id: "hist-29-1900",
    date: "2026-08-29",
    time: "19:00",
    project: "USIEM",
    task: "Graylog input SIEM stream",
    owner: "Agnes",
    verdict: "ok",
    note: "Log ingest normal 42.000 msg/s.",
  },
  {
    id: "hist-29-1700",
    date: "2026-08-29",
    time: "17:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Quota status sync sempurna.",
  },
  {
    id: "hist-29-1500",
    date: "2026-08-29",
    time: "15:00",
    project: "EPC Core",
    task: "Status layanan Catalog & Order",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Response time P99 180ms, pod sehat.",
  },
  {
    id: "hist-29-1300",
    date: "2026-08-29",
    time: "13:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Traffic flow stabil, producer aktif.",
  },

  // 28 Aug 2026
  {
    id: "hist-28-2200",
    date: "2026-08-28",
    time: "22:00",
    project: "EPC Core",
    task: "Kesiapan shift malam & integrasi EPC",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Semua parameter validasi batch malam siap.",
  },
  {
    id: "hist-28-2000",
    date: "2026-08-28",
    time: "20:00",
    project: "MB",
    task: "Push notification queue",
    owner: "Agnes",
    verdict: "ok",
    note: "Throughput notifikasi 8.200 push/menit.",
  },
  {
    id: "hist-28-1800",
    date: "2026-08-28",
    time: "18:00",
    project: "B2B",
    task: "Disk usage /apps pv-bbsvsoe1",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Disk usage mencapai 89.1%, peringatan awal.",
  },
  {
    id: "hist-28-1600",
    date: "2026-08-28",
    time: "16:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Grafana dashboards tersinkronisasi.",
  },
  {
    id: "hist-28-1400",
    date: "2026-08-28",
    time: "14:00",
    project: "APH",
    task: "Output Rate & Consumer Rate per PoP",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Consumer rate PoP 1-4 optimal.",
  },
  {
    id: "hist-28-1100",
    date: "2026-08-28",
    time: "11:00",
    project: "DM",
    task: "Utilisasi CPU Grafana",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "CPU usage rata-rata 42%.",
  },
  {
    id: "hist-28-0900",
    date: "2026-08-28",
    time: "09:00",
    project: "SM",
    task: "Queue ActiveMQ 228",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Queue kosong pasca-drain pagi.",
  },

  // 27 Aug 2026
  {
    id: "hist-27-2200",
    date: "2026-08-27",
    time: "22:00",
    project: "USIEM",
    task: "Graylog & Dashboard SIEM",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Audit stream ingest 38k msg/s.",
  },
  {
    id: "hist-27-2000",
    date: "2026-08-27",
    time: "20:00",
    project: "SM",
    task: "Queue fulldecode smng109",
    owner: "Agnes",
    verdict: "nok",
    note: "Spike antrian message hingga 5.100 item.",
  },
  {
    id: "hist-27-1800",
    date: "2026-08-27",
    time: "18:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Semua partition consumer tersinkronisasi.",
  },
  {
    id: "hist-27-1500",
    date: "2026-08-27",
    time: "15:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Validasi kuota harian tuntas.",
  },
  {
    id: "hist-27-1300",
    date: "2026-08-27",
    time: "13:00",
    project: "EPC Core",
    task: "Status layanan Catalog",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Pod catalog normal tanpa restart.",
  },
  {
    id: "hist-27-1000",
    date: "2026-08-27",
    time: "10:00",
    project: "APH",
    task: "Rebalance Consumer Area 1",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Rebalance sukses tanpa session timeout.",
  },

  // 26 Aug 2026
  {
    id: "hist-26-2200",
    date: "2026-08-26",
    time: "22:00",
    project: "SM",
    task: "Queue ActiveMQ 228 · 71 · 68",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Queue level stabil di bawah batas aman.",
  },
  {
    id: "hist-26-2000",
    date: "2026-08-26",
    time: "20:00",
    project: "MB",
    task: "Push notification queue",
    owner: "Agnes",
    verdict: "ok",
    note: "Latensi pengiriman notifikasi 120ms.",
  },
  {
    id: "hist-26-1700",
    date: "2026-08-26",
    time: "17:00",
    project: "B2B",
    task: "Disk usage /apps pv-bbsvsoe1",
    owner: "M. Ihsanul Arifin",
    verdict: "nok",
    note: "Volume mount log penuh 95%, rotasi manual.",
  },
  {
    id: "hist-26-1500",
    date: "2026-08-26",
    time: "15:00",
    project: "USIEM",
    task: "Graylog input SIEM stream",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Cluster Graylog green status.",
  },
  {
    id: "hist-26-1300",
    date: "2026-08-26",
    time: "13:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Alert rule engine responsif.",
  },
  {
    id: "hist-26-1000",
    date: "2026-08-26",
    time: "10:00",
    project: "EPC Core",
    task: "Status layanan Catalog & Order",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Order pipeline berjalan lancar.",
  },

  // 25 Aug 2026
  {
    id: "hist-25-2200",
    date: "2026-08-25",
    time: "22:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Topic partition lag normal.",
  },
  {
    id: "hist-25-1900",
    date: "2026-08-25",
    time: "19:00",
    project: "SM",
    task: "Queue ActiveMQ 228",
    owner: "Agnes",
    verdict: "ok",
    note: "Status broker ActiveMQ normal.",
  },
  {
    id: "hist-25-1600",
    date: "2026-08-25",
    time: "16:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Tidak ditemukan anomali kuota perangkat.",
  },
  {
    id: "hist-25-1400",
    date: "2026-08-25",
    time: "14:00",
    project: "APH",
    task: "Output Rate & Consumer Rate per PoP",
    owner: "Kristina Marbun",
    verdict: "nok",
    note: "PoP 3 mencatat penurunan consumer rate 35%.",
  },
  {
    id: "hist-25-1100",
    date: "2026-08-25",
    time: "11:00",
    project: "USIEM",
    task: "Graylog input SIEM stream",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "SIEM buffer utilisation 28%.",
  },
  {
    id: "hist-25-0800",
    date: "2026-08-25",
    time: "08:00",
    project: "EPC Core",
    task: "Status layanan Catalog",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Handover shift pagi terverifikasi.",
  },

  // 24 Aug 2026
  {
    id: "hist-24-2100",
    date: "2026-08-24",
    time: "21:00",
    project: "SM",
    task: "Queue fulldecode smng109",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Throughput consumer 450 msg/s.",
  },
  {
    id: "hist-24-1800",
    date: "2026-08-24",
    time: "18:00",
    project: "B2B",
    task: "Disk usage /apps pv-bbsvsoe1",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Disk usage 76.5% normal.",
  },
  {
    id: "hist-24-1500",
    date: "2026-08-24",
    time: "15:00",
    project: "MB",
    task: "Push notification queue",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Queue backlog 0.",
  },
  {
    id: "hist-24-1200",
    date: "2026-08-24",
    time: "12:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "All monitors green.",
  },
  {
    id: "hist-24-0900",
    date: "2026-08-24",
    time: "09:00",
    project: "DM",
    task: "Utilisasi CPU Grafana",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Load average stabil 1.4.",
  },

  // 23 Aug 2026
  {
    id: "hist-23-2200",
    date: "2026-08-23",
    time: "22:00",
    project: "USIEM",
    task: "Graylog & Dashboard SIEM",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Log indexing speed optimal.",
  },
  {
    id: "hist-23-1900",
    date: "2026-08-23",
    time: "19:00",
    project: "EPC Core",
    task: "Status layanan Catalog & Order",
    owner: "Agnes",
    verdict: "nok",
    note: "Timeout transient pada endpoint order catalog.",
  },
  {
    id: "hist-23-1600",
    date: "2026-08-23",
    time: "16:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Replikasi lintas broker Kafka aman.",
  },
  {
    id: "hist-23-1300",
    date: "2026-08-23",
    time: "13:00",
    project: "APH",
    task: "Output Rate & Consumer Rate per PoP",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Total throughput 55k pps stabil.",
  },
  {
    id: "hist-23-1000",
    date: "2026-08-23",
    time: "10:00",
    project: "SM",
    task: "Queue ActiveMQ 228",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Validasi queue normal.",
  },

  // 22 Aug 2026
  {
    id: "hist-22-2100",
    date: "2026-08-22",
    time: "21:00",
    project: "SM",
    task: "Queue ActiveMQ 228 · 71 · 68",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Semua broker queue berstatus healthy.",
  },
  {
    id: "hist-22-1800",
    date: "2026-08-22",
    time: "18:00",
    project: "DM",
    task: "Device quota LintasArta",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Sync quota berjalan otomatis.",
  },
  {
    id: "hist-22-1500",
    date: "2026-08-22",
    time: "15:00",
    project: "MB",
    task: "Push notification queue",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Throughput notifikasi lancar.",
  },
  {
    id: "hist-22-1200",
    date: "2026-08-22",
    time: "12:00",
    project: "USIEM",
    task: "Graylog input SIEM stream",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Throughput ingest normal.",
  },
  {
    id: "hist-22-0900",
    date: "2026-08-22",
    time: "09:00",
    project: "UNEM",
    task: "Layanan & alert Grafana",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "Semua node UNEM beroperasi nominal.",
  },

  // 21 Aug 2026
  {
    id: "hist-21-2200",
    date: "2026-08-21",
    time: "22:00",
    project: "B2B",
    task: "Traffic topik Kafka",
    owner: "M. Ihsanul Arifin",
    verdict: "ok",
    note: "Producer rate 2.400 msg/s stabil.",
  },
  {
    id: "hist-21-1900",
    date: "2026-08-21",
    time: "19:00",
    project: "SM",
    task: "Queue fulldecode smng109",
    owner: "Agnes",
    verdict: "nok",
    note: "Antrian pesan sempat menumpuk 2.900 item.",
  },
  {
    id: "hist-21-1600",
    date: "2026-08-21",
    time: "16:00",
    project: "EPC Core",
    task: "Status layanan Catalog & Order",
    owner: "Kristina Marbun",
    verdict: "ok",
    note: "Error rate katalog 0.00%.",
  },
  {
    id: "hist-21-1300",
    date: "2026-08-21",
    time: "13:00",
    project: "DM",
    task: "Utilisasi CPU Grafana",
    owner: "Mhd. Galih Khairi",
    verdict: "ok",
    note: "Utilisasi CPU rata-rata 38%.",
  },
  {
    id: "hist-21-1000",
    date: "2026-08-21",
    time: "10:00",
    project: "APH",
    task: "Output Rate & Consumer Rate per PoP",
    owner: "Pangondion Kurniawan",
    verdict: "ok",
    note: "PoP 1-4 output rate konsisten.",
  },
];

export function getOwnerRole(name: string): string {
  const normalized = name.toLowerCase().trim();
  if (normalized.includes("galih")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("pangondion")) return "Shift Lead (Shift Malam)";
  if (normalized.includes("kurnia")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("ihsanul") || normalized.includes("arifin")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("marbun") || normalized.includes("kristina")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("agnes")) return "L2 Specialist (Shift Malam)";
  if (normalized.includes("iqbal")) return "L2 Specialist (Shift Malam)";
  if (normalized.includes("sarah")) return "Incident Coordinator (Shift Malam)";
  if (normalized.includes("bagas")) return "Operator NOC (Shift Malam)";
  if (normalized.includes("dimas")) return "Infrastructure Engineer (Shift Pagi)";
  if (normalized.includes("malam")) return "NOC Shift Malam Team";
  return "Operator NOC (Shift Malam)";
}

export const seedTickets: Ticket[] = [
  // ── Today: 2026-08-31 ──
  {
    id: "86d4054rh",
    subject: "[EPC Tools] Tambah parameter baru untuk FMC",
    project: "EPC Tools",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "21:00",
    date: "2026-08-31",
    shift: "Malam",
    agingHours: 1.5,
    responseMinutes: 12,
    resolutionMinutes: 30,
    slaTargetMinutes: 120,
    description: "Permintaan konfigurasi parameter ambang FMC tambahan untuk mesin validasi EPC.",
    history: [
      {
        time: "21:00",
        type: "created",
        action: "Ticket dibuat untuk penambahan konfigurasi parameter ambang FMC pada mesin validasi EPC.",
        author: "Pangondion Kurniawan",
      },
      {
        time: "21:05",
        type: "user_request",
        action: "Requester follow up: Mohon update apakah threshold toleransi FMC dapat diset ke 85% untuk persiapan batch testing malam.",
        author: "Tim EPC (Budi Santoso)",
      },
      {
        time: "21:15",
        type: "response",
        action: "Tim merespon: Sedang memverifikasi ambang parameter FMC bersama tim EPC Tools dan mempersiapkan script validasi.",
        author: "Pangondion Kurniawan",
      },
      {
        time: "21:30",
        type: "status_change",
        action: "Tiket ditutup oleh Pangondion Kurniawan: Konfigurasi parameter ambang FMC 85% telah aktif dan pengujian validasi batch dinyatakan lulus.",
        author: "Pangondion Kurniawan",
      },
    ],
  },
  {
    id: "86d40esc1",
    subject: "[USIEM] Latency Spike pada Kafka SIEM Pipeline",
    project: "USIEM",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Mhd. Galih Khairi",
    status: "Escalated",
    created: "19:15",
    date: "2026-08-31",
    shift: "Malam",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Reza Rahardian (L2)",
    escalatedAt: "20:00",
    agingHours: 4.8,
    responseMinutes: 8,
    slaTargetMinutes: 60,
    rootCauseCategory: "Kafka Broker Sync",
    description: "Penumpukan lag consumer Kafka melebihi threshold 50.000 messages/sec, diekskalasikan ke tim infrastruktur L2.",
    history: [
      {
        time: "19:15",
        type: "created",
        action: "Ticket dibuat: Alert trigger lonjakan latency pada pipeline consumer Kafka SIEM terdeteksi melebihi threshold 50.000 msg/s.",
        author: "Mhd. Galih Khairi",
      },
      {
        time: "19:30",
        type: "user_request",
        action: "SOC Team request: Mohon percepat investigasi karena lag pipeline berpotensi menunda pengiriman event audit kepatuhan.",
        author: "SOC Team (Andi)",
      },
      {
        time: "20:00",
        type: "response",
        action: "Tim merespon: Ticket dieskalasikan ke Reza Rahardian (L2 Specialist) untuk re-sinkronisasi partisi broker Kafka cluster.",
        author: "Mhd. Galih Khairi",
      },
    ],
  },
  {
    id: "86d40eqn1",
    subject: "[EPC Tools] Validasi approval entities",
    project: "EPC Tools",
    severity: "Medium",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Pangondion Kurniawan",
    owners: ["Pangondion Kurniawan", "Mhd. Galih Khairi"],
    requestTime: "20:05",
    responseTime: "20:20",
    completionTime: "20:45",
    status: "Closed",
    created: "20:08",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 15,
    resolutionMinutes: 37,
    slaTargetMinutes: 60,
    description: "Validasi selesai untuk seluruh endpoint approval entities.",
    history: [
      {
        time: "20:08",
        type: "created",
        action: "Ticket dibuat untuk validasi kelengkapan seluruh endpoint approval entities pada portal EPC.",
        author: "Pangondion Kurniawan",
      },
      {
        time: "20:15",
        type: "user_request",
        action: "Requester follow up: Mohon konfirmasi apakah endpoint batch approval entities sudah dapat diakses tanpa connection timeout.",
        author: "Tim EPC (Teresa)",
      },
      {
        time: "20:25",
        type: "response",
        action: "Tim merespon: Sedang melakukan verifikasi koneksi pool service dan reset cache routing approval.",
        author: "Pangondion Kurniawan",
      },
      {
        time: "20:45",
        type: "status_change",
        action: "Tiket ditutup oleh Pangondion Kurniawan: Validasi selesai untuk seluruh endpoint approval entities dan verifikasi berjalan normal.",
        author: "Pangondion Kurniawan",
      },
    ],
  },
  {
    id: "86d40cxuk",
    subject: "[SM] Transfer file buffer LTE",
    project: "SM",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "18:20",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 10,
    resolutionMinutes: 40,
    slaTargetMinutes: 120,
    description: "File buffer log LTE ditransfer ke node arsip sekunder.",
    history: [
      {
        time: "18:20",
        type: "created",
        action: "Ticket dibuat untuk transfer file buffer log LTE ke node arsip sekunder.",
        author: "Mhd. Galih Khairi",
      },
      {
        time: "18:35",
        type: "user_request",
        action: "Requester request: Mohon pastikan integritas checksum MD5 tervalidasi sebelum file buffer di server utama dihapus.",
        author: "Tim Data Warehouse",
      },
      {
        time: "18:45",
        type: "response",
        action: "Tim merespon: Proses pemindahan file buffer ke node arsip sekunder sedang berjalan dan checksum dalam antrean.",
        author: "Mhd. Galih Khairi",
      },
      {
        time: "19:00",
        type: "status_change",
        action: "Tiket ditutup oleh Mhd. Galih Khairi: Transfer file buffer selesai dan checksum tervalidasi 100%.",
        author: "Mhd. Galih Khairi",
      },
    ],
  },
  {
    id: "86d40b9yh",
    subject: "[USIEM] Restart gateway log SIEM",
    project: "USIEM",
    severity: "Low",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "16:29",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 5,
    resolutionMinutes: 20,
    slaTargetMinutes: 60,
    description: "Restart gateway rutin setelah akumulasi memori socket minor.",
    history: [{ time: "16:29", action: "Gateway berhasil di-restart", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40bebu",
    subject: "[MB] Kirim event notifikasi push",
    project: "MB",
    severity: "Low",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "16:21",
    date: "2026-08-31",
    shift: "Malam",
    responseMinutes: 8,
    resolutionMinutes: 18,
    slaTargetMinutes: 60,
    description: "Laju queue pengiriman push notification mobile terverifikasi.",
    history: [{ time: "16:21", action: "Kondisi queue nominal terverifikasi", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40m01x",
    subject: "[B2B] Disk Space Alert pv-bbsvsoe1-ctl08 (>92%)",
    project: "B2B",
    severity: "High",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "03:40",
    date: "2026-08-31",
    shift: "Subuh",
    agingHours: 2.2,
    responseMinutes: 6,
    slaTargetMinutes: 60,
    description: "Kapasitas partisi /apps meningkat pesat saat pembersihan log malam.",
    history: [
      {
        time: "03:40",
        type: "created",
        action: "Ticket dibuat dari alert pemantauan: kapasitas partisi /apps mencapai 92% saat pembersihan log malam.",
        author: "M. Ihsanul Arifin",
      },
      {
        time: "03:50",
        type: "user_request",
        action: "Infra Alert request: Mohon segera eksekusi pembersihan direktori temp sebelum partisi mencapai batas 95%.",
        author: "Infra Monitoring Alert",
      },
      {
        time: "04:05",
        type: "response",
        action: "Tim merespon: Pembersihan berkas dump sementara dan kompresi arsip log sedang dieksekusi.",
        author: "M. Ihsanul Arifin",
      },
    ],
  },
  {
    id: "86d40dm01",
    subject: "[DM] Polling SNMP Over-Threshold PoP Balikpapan",
    project: "DM",
    severity: "Medium",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "10:15",
    date: "2026-08-31",
    shift: "Pagi",
    responseMinutes: 7,
    resolutionMinutes: 28,
    slaTargetMinutes: 60,
    description: "Normalisasi packet loss SNMP pada router edge Balikpapan.",
    history: [
      {
        time: "10:15",
        type: "created",
        action: "Ticket dibuat: Alert latensi polling SNMP router edge Balikpapan melebihi ambang batas toleransi.",
        author: "Kristina Marbun",
      },
      {
        time: "10:20",
        type: "user_request",
        action: "NOC Regional request: Mohon lakukan pengecekan flapping link peering transit Balikpapan.",
        author: "NOC Regional Kalimantan",
      },
      {
        time: "10:28",
        type: "response",
        action: "Tim merespon: Route flapping distabilkan dan peering transit sekunder diaktifkan.",
        author: "Kristina Marbun",
      },
      {
        time: "10:43",
        type: "status_change",
        action: "Tiket ditutup oleh Kristina Marbun: Polling SNMP kembali stabil dan baseline performa tervalidasi normal.",
        author: "Kristina Marbun",
      },
    ],
  },
  {
    id: "86d40un01",
    subject: "[UNEM] Penambahan Alert Rules Prometheus Disk Latency",
    project: "UNEM",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "11:40",
    date: "2026-08-31",
    shift: "Pagi",
    responseMinutes: 14,
    resolutionMinutes: 42,
    slaTargetMinutes: 120,
    description: "Aturan alerting baru untuk I/O wait waktu respon disk terpasang.",
    history: [{ time: "11:40", action: "Alert rule deployed", author: "Kristina Marbun" }],
  },

  // ── Yesterday: 2026-08-30 ──
  {
    id: "86d40y02a",
    subject: "[APH] Rebalance Consumer Area 1 CGNAT F5",
    project: "APH",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "14:10",
    date: "2026-08-30",
    shift: "Pagi",
    responseMinutes: 14,
    resolutionMinutes: 52,
    slaTargetMinutes: 60,
    description: "Penyesuaian distribusi rate Egress F5 untuk menghindari throttling.",
    history: [{ time: "14:10", action: "Konfigurasi rebalance diterapkan", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40esc2",
    subject: "[EPC Tools] Memory Leak pada Catalog Service Pods",
    project: "EPC Tools",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "22:15",
    date: "2026-08-30",
    shift: "Malam",
    escalationLevel: "L3 Incident Coordinator",
    escalatedTo: "Dimas Suryo (L3 Lead)",
    escalatedAt: "23:00",
    responseMinutes: 10,
    resolutionMinutes: 75,
    slaTargetMinutes: 60,
    rootCauseCategory: "Memory Saturation",
    description: "Pod catalog crash berulang di cluster k8s node-04, eskalasi L3 koordinasi dengan dev infra.",
    history: [
      { time: "22:15", action: "Crashloop terdeteksi", author: "M. Ihsanul Arifin" },
      { time: "23:30", action: "Patch buffer hotspot diterapkan", author: "Dimas Suryo" },
    ],
  },
  {
    id: "86d40sm02",
    subject: "[SM] Penumpukan Queue ActiveMQ smng109",
    project: "SM",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "17:45",
    date: "2026-08-30",
    shift: "Malam",
    responseMinutes: 6,
    resolutionMinutes: 48,
    slaTargetMinutes: 60,
    description: "Consumer rate ActiveMQ ditingkatkan untuk mengosongkan 4.200 antrean log.",
    history: [{ time: "17:45", action: "Thread consumer dinaikkan", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40b2b02",
    subject: "[B2B] Re-sync Partisi Topic Kafka Billing",
    project: "B2B",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "08:30",
    date: "2026-08-30",
    shift: "Pagi",
    responseMinutes: 11,
    resolutionMinutes: 35,
    slaTargetMinutes: 60,
    description: "Leader partition rebalance pada cluster Kafka B2B.",
    history: [{ time: "08:30", action: "Rebalance sukses", author: "Agnes" }],
  },

  // ── Earlier This Week: 2026-08-29 ──
  {
    id: "86d4029a1",
    subject: "[MB] Database Connection Pool Saturation",
    project: "MB",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "19:20",
    date: "2026-08-29",
    shift: "Malam",
    responseMinutes: 8,
    resolutionMinutes: 41,
    slaTargetMinutes: 60,
    description: "Idle connection cleanup pada pool database notification service.",
    history: [{ time: "19:20", action: "Pool connection recycled", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d4029a2",
    subject: "[APH] Audit Egress Traffic Roaming Data",
    project: "APH",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "14:00",
    date: "2026-08-29",
    shift: "Pagi",
    responseMinutes: 18,
    resolutionMinutes: 50,
    slaTargetMinutes: 120,
    description: "Rekap traffic harian PoP 1 sampai 4 untuk laporan audit.",
    history: [{ time: "14:00", action: "Data export tervalidasi", author: "Kristina Marbun" }],
  },
  {
    id: "86d4029a3",
    subject: "[L2] Penyusunan RCA Incident Intermittent Gateway",
    project: "L2",
    severity: "Medium",
    type: "Other",
    category: "Knowledge Management & Documentation",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "11:15",
    date: "2026-08-29",
    shift: "Pagi",
    responseMinutes: 12,
    resolutionMinutes: 65,
    slaTargetMinutes: 120,
    description: "Penyusunan Root Cause Analysis untuk review manajemen insiden.",
    history: [{ time: "11:15", action: "Dokumen RCA diunggah", author: "Pangondion Kurniawan" }],
  },

  // ── Earlier This Week: 2026-08-28 ──
  {
    id: "86d40w03k",
    subject: "[DM] Sinkronisasi Device Quota LintasArta",
    project: "DM",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "09:30",
    date: "2026-08-28",
    shift: "Pagi",
    responseMinutes: 9,
    resolutionMinutes: 45,
    slaTargetMinutes: 60,
    description: "Database sync over-quota pulih setelah reload daemon worker.",
    history: [{ time: "09:30", action: "Reload worker daemon", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d4028b1",
    subject: "[USIEM] Pembersihan Indeks Elastic Log Expired",
    project: "USIEM",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "02:15",
    date: "2026-08-28",
    shift: "Subuh",
    responseMinutes: 10,
    resolutionMinutes: 30,
    slaTargetMinutes: 120,
    description: "Indeks lama dirotasi ke cold storage untuk membebaskan 1.2 TB.",
    history: [{ time: "02:15", action: "Index lifecycle management executed", author: "Agnes" }],
  },
  {
    id: "86d4028b2",
    subject: "[EPC Tools] Export Rekap Validasi Order Bulanan",
    project: "EPC Tools",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "15:40",
    date: "2026-08-28",
    shift: "Pagi",
    responseMinutes: 12,
    resolutionMinutes: 25,
    slaTargetMinutes: 60,
    description: "Ekspor rekap query analitik untuk divisi EPC.",
    history: [{ time: "15:40", action: "File CSV dikirim", author: "Mhd. Galih Khairi" }],
  },

  // ── Earlier This Week: 2026-08-27 ──
  {
    id: "86d4027a1",
    subject: "[SM] Upstream Telco SS7 Gateway Timeouts",
    project: "SM",
    severity: "Critical",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "20:10",
    date: "2026-08-27",
    shift: "Malam",
    responseMinutes: 7,
    resolutionMinutes: 88,
    slaTargetMinutes: 60,
    rootCauseCategory: "Upstream Vendor / ISP",
    description: "Timeout koneksi gateway SS7 dari upstream provider; switchover ke link cadangan.",
    history: [
      { time: "20:10", action: "Incident terdeteksi", author: "Pangondion Kurniawan" },
      { time: "21:38", action: "Failover tuntas", author: "Pangondion Kurniawan" },
    ],
  },
  {
    id: "86d4027a2",
    subject: "[B2B] Tambah Node Kafka Broker 04",
    project: "B2B",
    severity: "Medium",
    type: "Change Request",
    category: "Change Request",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "13:00",
    date: "2026-08-27",
    shift: "Pagi",
    responseMinutes: 15,
    resolutionMinutes: 55,
    slaTargetMinutes: 120,
    description: "Pemasangan dan join cluster node broker Kafka tambahan.",
    history: [{ time: "13:00", action: "Broker joined cluster", author: "Kristina Marbun" }],
  },
  {
    id: "86d4027a3",
    subject: "[UNEM] Audit Dashboard Grafana NOC Shift Room",
    project: "UNEM",
    severity: "Low",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "09:00",
    date: "2026-08-27",
    shift: "Pagi",
    responseMinutes: 10,
    resolutionMinutes: 30,
    slaTargetMinutes: 60,
    description: "Pemeriksaan konsistensi metrik panel TV monitoring.",
    history: [{ time: "09:00", action: "Verifikasi OK", author: "M. Ihsanul Arifin" }],
  },

  // ── Earlier This Week: 2026-08-26 & 2026-08-25 ──
  {
    id: "86d4026a1",
    subject: "[APH] Spike Packet Drop pada PoP Jakarta 2",
    project: "APH",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "16:45",
    date: "2026-08-26",
    shift: "Malam",
    responseMinutes: 6,
    resolutionMinutes: 34,
    slaTargetMinutes: 60,
    description: "Penyesuaian MTU pada switch interface PoP Jakarta 2.",
    history: [{ time: "16:45", action: "MTU tuned to 9000 jumbo frame", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d4026a2",
    subject: "[MB] Maintenance Sertifikat SSL Webhook Gateway",
    project: "MB",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Agnes",
    status: "Closed",
    created: "01:30",
    date: "2026-08-26",
    shift: "Subuh",
    responseMinutes: 12,
    resolutionMinutes: 28,
    slaTargetMinutes: 60,
    description: "Perpanjangan sertifikat TLS wildcard domain notification push.",
    history: [{ time: "01:30", action: "Certificate renewed and nginx reloaded", author: "Agnes" }],
  },
  {
    id: "86d4025a1",
    subject: "[EPC Tools] Konfigurasi Filter Rule Automation Baru",
    project: "EPC Tools",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "14:20",
    date: "2026-08-25",
    shift: "Pagi",
    responseMinutes: 16,
    resolutionMinutes: 39,
    slaTargetMinutes: 120,
    description: "Rule filter validasi nomor MSISDN VIP ditambahkan.",
    history: [{ time: "14:20", action: "Rules activated in engine", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d4025a2",
    subject: "[USIEM] Alarm Disk Warning pada Node SIEM-02",
    project: "USIEM",
    severity: "High",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "04:10",
    date: "2026-08-25",
    shift: "Subuh",
    responseMinutes: 9,
    resolutionMinutes: 44,
    slaTargetMinutes: 60,
    description: "Pembersihan dump log gzip lama di /data/siem.",
    history: [{ time: "04:10", action: "Disk usage down to 64%", author: "M. Ihsanul Arifin" }],
  },

  // ── Open / Backlog Aging Spectrum representation ──
  {
    id: "86d40bg01",
    subject: "[L2] Koordinasi Perbaikan Skema Partisi Database Arsip",
    project: "L2",
    severity: "Medium",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Galih Khairi",
    status: "Pending",
    created: "10:00",
    date: "2026-08-29",
    shift: "Pagi",
    agingHours: 52.0,
    responseMinutes: 15,
    slaTargetMinutes: 120,
    description: "Menunggu jadwal maintenance window akhir pekan bersama tim DBA.",
    history: [{ time: "10:00", action: "Ticket dipending menunggu window maintenance", author: "Galih Khairi" }],
  },
  {
    id: "86d40bg02",
    subject: "[DM] Penggantian Modul Transceiver SFP Ruang Server DM",
    project: "DM",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Kristina Marbun",
    status: "Pending",
    created: "09:00",
    date: "2026-08-28",
    shift: "Pagi",
    agingHours: 76.5,
    responseMinutes: 22,
    slaTargetMinutes: 120,
    description: "Menunggu pengiriman suku cadang modul SFP dari vendor LintasArta.",
    history: [{ time: "09:00", action: "Vendor order placed", author: "Kristina Marbun" }],
  },

  // ── Last Month Baseline (July 2026) ──
  {
    id: "86d40p04m",
    subject: "[L2] Audit SOP Incident Coordinator Shift Handover",
    project: "L2",
    severity: "Low",
    type: "Other",
    category: "Knowledge Management & Documentation",
    owner: "Galih Khairi",
    status: "Closed",
    created: "11:00",
    date: "2026-07-15",
    shift: "Pagi",
    responseMinutes: 20,
    resolutionMinutes: 90,
    slaTargetMinutes: 120,
    description: "Dokumentasi SOP perbaikan matriks eskalasi diperbarui.",
    history: [{ time: "11:00", action: "Dokumen SOP diarsipkan ke Runbooks", author: "Galih Khairi" }],
  },
  {
    id: "86d40prev1",
    subject: "[UNEM] Penyesuaian Dashboard Grafana Core Services",
    project: "UNEM",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Galih Khairi",
    status: "Closed",
    created: "15:00",
    date: "2026-07-25",
    shift: "Pagi",
    responseMinutes: 18,
    resolutionMinutes: 60,
    slaTargetMinutes: 120,
    description: "Panel alerting Grafana ditambahkan untuk metrik CPU Core.",
    history: [{ time: "15:00", action: "Dashboard updated", author: "Galih Khairi" }],
  },
  {
    id: "86d40prev2",
    subject: "[SM] Patch Keamanan ActiveMQ Cluster",
    project: "SM",
    severity: "High",
    type: "Maintenance",
    category: "Maintenance",
    owner: "M. Ihsanul Arifin",
    status: "Closed",
    created: "01:00",
    date: "2026-07-20",
    shift: "Subuh",
    responseMinutes: 10,
    resolutionMinutes: 50,
    slaTargetMinutes: 60,
    description: "Security patch rollover pada broker cluster.",
    history: [{ time: "01:00", action: "Patch applied", author: "M. Ihsanul Arifin" }],
  },

  // ── September 2026: Simulated Extended Dataset (for Pagination & Scale Testing) ──
  {
    id: "86d40sep01",
    subject: "[USIEM] Lonjakan Event Ingestion Log SIEM Node 3",
    project: "USIEM",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Mhd. Galih Khairi",
    status: "Escalated",
    created: "08:15",
    date: "2026-09-11",
    shift: "Pagi",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Reza Rahardian (L2)",
    escalatedAt: "08:45",
    agingHours: 5.2,
    responseMinutes: 10,
    slaTargetMinutes: 60,
    rootCauseCategory: "Buffer Saturation",
    description: "Lonjakan volume log firewall melebihi batas buffer parser Graylog SIEM.",
    history: [{ time: "08:15", action: "Ticket dibuat: Ingestion spike terdeteksi", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40sep02",
    subject: "[SM] Flapping Interface Link Trunk Core SM-MB",
    project: "SM",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Pangondion Kurniawan",
    status: "Escalated",
    created: "09:30",
    date: "2026-09-11",
    shift: "Pagi",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Budi Santoso (L2 Network)",
    escalatedAt: "09:50",
    agingHours: 3.8,
    responseMinutes: 8,
    slaTargetMinutes: 60,
    rootCauseCategory: "Physical Link Flap",
    description: "Flapping link trunk SM-MB menyebabkan degradasi transmisi paket.",
    history: [{ time: "09:30", action: "Ticket dibuat: Link flapping", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40sep03",
    subject: "[EPC Tools] Validasi Payload Schema JSON Sync API",
    project: "EPC Tools",
    severity: "Medium",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Agnes",
    status: "Active",
    created: "10:10",
    date: "2026-09-11",
    shift: "Pagi",
    agingHours: 2.1,
    responseMinutes: 14,
    slaTargetMinutes: 120,
    description: "Permintaan validasi skema payload JSON untuk integrasi billing partner.",
    history: [{ time: "10:10", action: "Ticket dibuat", author: "Agnes" }],
  },
  {
    id: "86d40sep04",
    subject: "[B2B] Throttling Request API Gateway Transaksi Mitra",
    project: "B2B",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "M. Ihsanul Arifin",
    status: "Escalated",
    created: "10:45",
    date: "2026-09-11",
    shift: "Pagi",
    escalationLevel: "L3 Incident Coordinator",
    escalatedTo: "Dimas Suryo (L3 Lead)",
    escalatedAt: "11:15",
    agingHours: 2.5,
    responseMinutes: 6,
    slaTargetMinutes: 60,
    rootCauseCategory: "Rate Limit Misconfig",
    description: "Mitra korporat mengalami 429 Too Many Requests akibat batas rate limit terlampaui.",
    history: [{ time: "10:45", action: "Eskalasi ke L3 Coordinator", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40sep05",
    subject: "[DM] Monitoring Peningkatan Storage Mount /data/audit",
    project: "DM",
    severity: "Low",
    type: "Monitoring Alert",
    category: "Monitoring VM, Platform & Services",
    owner: "Kristina Marbun",
    status: "Active",
    created: "11:00",
    date: "2026-09-11",
    shift: "Pagi",
    agingHours: 1.8,
    responseMinutes: 15,
    slaTargetMinutes: 120,
    description: "Partisi storage audit mencapai 78%, pemantauan berkala shift pagi.",
    history: [{ time: "11:00", action: "Alert terverifikasi", author: "Kristina Marbun" }],
  },
  {
    id: "86d40sep06",
    subject: "[APH] Latensi RTT Tinggi Antara Hub Medan & Batam",
    project: "APH",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Mhd. Galih Khairi",
    status: "Escalated",
    created: "07:20",
    date: "2026-09-10",
    shift: "Subuh",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Faisal (Transport L2)",
    escalatedAt: "07:50",
    agingHours: 28.5,
    responseMinutes: 9,
    slaTargetMinutes: 60,
    rootCauseCategory: "Submarine Cable Attenuation",
    description: "Penurunan kualitas kabel bawah laut jalur Batam-Medan memicu latency spike.",
    history: [{ time: "07:20", action: "Eskalasi ke tim transport", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40sep07",
    subject: "[MB] Restart Service Daemon Push Notifikasi",
    project: "MB",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "02:00",
    date: "2026-09-10",
    shift: "Subuh",
    responseMinutes: 5,
    resolutionMinutes: 20,
    slaTargetMinutes: 60,
    description: "Daemon push notifikasi berhasil di-restart berkala tanpa error log.",
    history: [{ time: "02:20", action: "Service normal", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40sep08",
    subject: "[UNEM] Penyesuaian Poller SNMP Perangkat Edge Bali",
    project: "UNEM",
    severity: "Medium",
    type: "Change Request",
    category: "Change Request",
    owner: "Agnes",
    status: "Closed",
    created: "14:15",
    date: "2026-09-10",
    shift: "Pagi",
    responseMinutes: 12,
    resolutionMinutes: 40,
    slaTargetMinutes: 120,
    description: "Interval poller diubah dari 30s ke 60s untuk menurunkan beban CPU perangkat edge.",
    history: [{ time: "14:55", action: "Konfigurasi aktif", author: "Agnes" }],
  },
  {
    id: "86d40sep09",
    subject: "[EPC Tools] High CPU Utilization Worker Batch ETL",
    project: "EPC Tools",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "M. Ihsanul Arifin",
    status: "Escalated",
    created: "21:30",
    date: "2026-09-09",
    shift: "Malam",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Reza Rahardian (L2)",
    escalatedAt: "22:00",
    agingHours: 42.0,
    responseMinutes: 11,
    slaTargetMinutes: 60,
    rootCauseCategory: "Unindexed Query Lock",
    description: "Worker batch ETL terkunci pada query agregasi tanpa indeks.",
    history: [{ time: "21:30", action: "Eskalasi ke L2 DB specialist", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40sep10",
    subject: "[USIEM] Sinkronisasi Sertifikat Mutual TLS Syslog-ng",
    project: "USIEM",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Kristina Marbun",
    status: "Pending",
    created: "16:00",
    date: "2026-09-09",
    shift: "Pagi",
    agingHours: 48.0,
    responseMinutes: 20,
    slaTargetMinutes: 120,
    description: "Menunggu penerbitan CA internal baru dari tim Information Security.",
    history: [{ time: "16:00", action: "Pending sertifikat CA", author: "Kristina Marbun" }],
  },
  {
    id: "86d40sep11",
    subject: "[SM] Antrian Pesan Tertunda pada Broker SM-Broker-02",
    project: "SM",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Mhd. Galih Khairi",
    status: "Escalated",
    created: "13:40",
    date: "2026-09-08",
    shift: "Pagi",
    escalationLevel: "L3 Incident Coordinator",
    escalatedTo: "Dimas Suryo (L3 Lead)",
    escalatedAt: "14:00",
    agingHours: 68.0,
    responseMinutes: 7,
    slaTargetMinutes: 60,
    rootCauseCategory: "Disk I/O Choke",
    description: "Broker mengalami I/O choke saat persisten journal flush ke SAN storage.",
    history: [{ time: "13:40", action: "Eskalasi L3", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40sep12",
    subject: "[B2B] Request Whitelist IP Mitra Pembayaran Baru",
    project: "B2B",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "11:20",
    date: "2026-09-08",
    shift: "Pagi",
    responseMinutes: 15,
    resolutionMinutes: 30,
    slaTargetMinutes: 120,
    description: "CIDR blok IP mitra berhasil didaftarkan pada firewall WAF ingress.",
    history: [{ time: "11:50", action: "Whitelist sukses", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40sep13",
    subject: "[DM] Verifikasi Rekonsiliasi Log Penggunaan Kuota",
    project: "DM",
    severity: "Medium",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Agnes",
    status: "Closed",
    created: "09:00",
    date: "2026-09-07",
    shift: "Pagi",
    responseMinutes: 8,
    resolutionMinutes: 45,
    slaTargetMinutes: 60,
    description: "Pemeriksaan cross-check antara billing data warehouse dan gateway DM.",
    history: [{ time: "09:45", action: "Laporan diverifikasi", author: "Agnes" }],
  },
  {
    id: "86d40sep14",
    subject: "[APH] Pemeliharaan Perangkat Switch Spine DC Cikarang",
    project: "APH",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "M. Ihsanul Arifin",
    status: "Escalated",
    created: "23:00",
    date: "2026-09-07",
    shift: "Malam",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Budi Santoso (L2 Network)",
    escalatedAt: "23:30",
    agingHours: 89.0,
    responseMinutes: 10,
    slaTargetMinutes: 60,
    rootCauseCategory: "Power Supply Fault",
    description: "Modul PSU redundan switch spine mati, menunggu penggantian spare part tim vendor.",
    history: [{ time: "23:00", action: "Eskalasi vendor hardware", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40sep15",
    subject: "[USIEM] Parser Error pada Log Format CEF Checkpoint",
    project: "USIEM",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Kristina Marbun",
    status: "Escalated",
    created: "15:10",
    date: "2026-09-06",
    shift: "Pagi",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Reza Rahardian (L2)",
    escalatedAt: "15:40",
    agingHours: 110.0,
    responseMinutes: 12,
    slaTargetMinutes: 60,
    rootCauseCategory: "Regex Parser Failure",
    description: "Format ekstensi baru log Checkpoint tidak terparsing pada field extraction rule.",
    history: [{ time: "15:10", action: "Eskalasi perbaikan parser", author: "Kristina Marbun" }],
  },
  {
    id: "86d40sep16",
    subject: "[MB] Pengujian Failover Cluster RabbitMQ Node 1 ke Node 2",
    project: "MB",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "03:00",
    date: "2026-09-06",
    shift: "Subuh",
    responseMinutes: 6,
    resolutionMinutes: 50,
    slaTargetMinutes: 60,
    description: "Simulasi failover cluster sukses tanpa ada antrian pesan yang hilang.",
    history: [{ time: "03:50", action: "Failover verified", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40sep17",
    subject: "[EPC Tools] Permintaan Akses Akun Service Operator Baru",
    project: "EPC Tools",
    severity: "Low",
    type: "Ad-hoc Request",
    category: "Ad-hoc Request",
    owner: "Pangondion Kurniawan",
    status: "Closed",
    created: "10:30",
    date: "2026-09-05",
    shift: "Pagi",
    responseMinutes: 10,
    resolutionMinutes: 20,
    slaTargetMinutes: 120,
    description: "Pemberian hak akses role viewer analitik portal EPC Tools.",
    history: [{ time: "10:50", action: "Akses dibuat", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40sep18",
    subject: "[SM] Koreksi Routing Tabel BGP Transit Telekomunikasi",
    project: "SM",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Agnes",
    status: "Escalated",
    created: "17:45",
    date: "2026-09-04",
    shift: "Pagi",
    escalationLevel: "L3 Incident Coordinator",
    escalatedTo: "Dimas Suryo (L3 Lead)",
    escalatedAt: "18:15",
    agingHours: 160.0,
    responseMinutes: 8,
    slaTargetMinutes: 60,
    rootCauseCategory: "BGP Prefix Leak",
    description: "Rute prefix leak eksternal mengakibatkan lonjakan transit asimetris.",
    history: [{ time: "17:45", action: "Eskalasi ke L3 Coordinator", author: "Agnes" }],
  },
  {
    id: "86d40sep19",
    subject: "[UNEM] Update Firmware Switch Distribution Surabaya",
    project: "UNEM",
    severity: "Medium",
    type: "Maintenance",
    category: "Maintenance",
    owner: "M. Ihsanul Arifin",
    status: "Pending",
    created: "22:00",
    date: "2026-09-03",
    shift: "Malam",
    agingHours: 180.0,
    responseMinutes: 15,
    slaTargetMinutes: 120,
    description: "Menunggu approval jadwal pemadaman terjadwal dari regional Jawa Timur.",
    history: [{ time: "22:00", action: "Pending maintenance approval", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40sep20",
    subject: "[B2B] Penurunan Throughput Transaksi Settlement",
    project: "B2B",
    severity: "High",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Kristina Marbun",
    status: "Escalated",
    created: "14:00",
    date: "2026-09-02",
    shift: "Pagi",
    escalationLevel: "L2 Specialist",
    escalatedTo: "Reza Rahardian (L2)",
    escalatedAt: "14:30",
    agingHours: 215.0,
    responseMinutes: 9,
    slaTargetMinutes: 60,
    rootCauseCategory: "DB Connection Pool Exhaustion",
    description: "Koneksi pool database settlement habis akibat query lambat tak tertutup.",
    history: [{ time: "14:00", action: "Eskalasi L2 DBA", author: "Kristina Marbun" }],
  },
  {
    id: "86d40sep21",
    subject: "[APH] Optimasi Egress F5 Shaper Area 2",
    project: "APH",
    severity: "Low",
    type: "Change Request",
    category: "Change Request",
    owner: "Mhd. Galih Khairi",
    status: "Closed",
    created: "11:00",
    date: "2026-09-02",
    shift: "Pagi",
    responseMinutes: 14,
    resolutionMinutes: 35,
    slaTargetMinutes: 120,
    description: "Shaper bandwidth disesuaikan untuk mengantisipasi lonjakan trafik siang.",
    history: [{ time: "11:35", action: "Profil QoS diperbarui", author: "Mhd. Galih Khairi" }],
  },
  {
    id: "86d40sep22",
    subject: "[DM] Troubleshooting Alarm Interface Flap DM-GW-01",
    project: "DM",
    severity: "High",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "Pangondion Kurniawan",
    status: "Active",
    created: "08:30",
    date: "2026-09-01",
    shift: "Pagi",
    agingHours: 240.0,
    responseMinutes: 10,
    slaTargetMinutes: 60,
    description: "Pemeriksaan CRC error pada port uplink fiber optik DM Gateway.",
    history: [{ time: "08:30", action: "Sedang investigasi fisik port", author: "Pangondion Kurniawan" }],
  },
  {
    id: "86d40sep23",
    subject: "[USIEM] Eskalasi Temuan Keamanan Brute Force Akun Privileged",
    project: "USIEM",
    severity: "Critical",
    type: "Escalation",
    category: "Escalation Handling",
    owner: "Agnes",
    status: "Escalated",
    created: "01:20",
    date: "2026-09-01",
    shift: "Subuh",
    escalationLevel: "L3 Incident Coordinator",
    escalatedTo: "Dimas Suryo (L3 Lead)",
    escalatedAt: "01:45",
    agingHours: 250.0,
    responseMinutes: 5,
    slaTargetMinutes: 60,
    rootCauseCategory: "Security Incident Alert",
    description: "Terdeteksi percobaan login berulang pada akun root bastion host dari IP luar.",
    history: [{ time: "01:20", action: "Eskalasi darurat ke tim Security", author: "Agnes" }],
  },
  {
    id: "86d40sep24",
    subject: "[MB] Pemulihan Antrian Dead Letter Exchange RabbitMQ",
    project: "MB",
    severity: "Medium",
    type: "Incident",
    category: "Incident & Issue Handling",
    owner: "M. Ihsanul Arifin",
    status: "Active",
    created: "15:00",
    date: "2026-09-01",
    shift: "Pagi",
    agingHours: 235.0,
    responseMinutes: 12,
    slaTargetMinutes: 60,
    description: "Pesan tertolak dialihkan kembali ke worker setelah bug serialisasi diperbaiki.",
    history: [{ time: "15:00", action: "Requeue messages in progress", author: "M. Ihsanul Arifin" }],
  },
  {
    id: "86d40sep25",
    subject: "[EPC Tools] Penjadwalan Backup Snapshot Harian Storage",
    project: "EPC Tools",
    severity: "Low",
    type: "Maintenance",
    category: "Maintenance",
    owner: "Kristina Marbun",
    status: "Closed",
    created: "04:00",
    date: "2026-09-01",
    shift: "Subuh",
    responseMinutes: 8,
    resolutionMinutes: 25,
    slaTargetMinutes: 60,
    description: "Snapshot storage volume berhasil tersimpan di cluster backup cold tier.",
    history: [{ time: "04:25", action: "Backup verifikasi OK", author: "Kristina Marbun" }],
  },
];

export const initialHandoverTasks: HandoverTask[] = [
  { id: 1, taskTemplateId: "standard-1", isNewlyAdded: false, title: "Pemantauan Dump Automation EPC Tools", project: "EPC Tools", detail: "Perketat pemantauan Dump Automation. Pengecekan dapat menggunakan akun Teresa rosikin2011_x.", state: "repeat", completed: true },
  { id: 2, taskTemplateId: "standard-2", isNewlyAdded: false, title: "Pengecekan Email L2 Support di akhir shift", project: "L2", detail: "Pastikan seluruh folder sudah dibaca dan tidak ada request yang terlewat.", state: "repeat", completed: true },
  { id: 3, taskTemplateId: "standard-3", isNewlyAdded: false, title: "Monitoring penumpukan fulldecode SM", project: "SM", detail: "Pantau queue fulldecode pada ActiveMQ 228 dan direktori output smng109.", state: "repeat", completed: true },
  { id: 4, taskTemplateId: "standard-4", isNewlyAdded: false, title: "Monitoring disk usage B2B Prod", project: "B2B", detail: "Pantau /apps pada pv-bbsvsoe1-ctl08-20:9100; informasikan ke Mas Alfiant apabila mencapai 98%.", state: "repeat", completed: true },
  { id: 5, taskTemplateId: "standard-5", isNewlyAdded: false, title: "Monitoring performa APH per jam", project: "APH", detail: "Pantau Output Rate, APH Consumer Rate, serta Egress Listener F5 CGNAT Area 1 per PoP dan laporkan ke Teams APH.", state: "repeat", completed: true },
  { id: 6, taskTemplateId: "standard-6", isNewlyAdded: false, title: "Report Repsoses file Excel SM", project: "SM", detail: "Kirim report hasil Repsoses dari tim Solusi ke grup WA SM-MB Support Tritronik pada pagi dan malam hari.", state: "repeat", completed: true },
  { id: 7, taskTemplateId: "standard-7", isNewlyAdded: false, title: "Volume Roamware dan Backup SM", project: "SM", detail: "Lakukan pengisian di akhir shift serta monitoring total volume Huawei SGW.", state: "repeat", completed: true },
  { id: 8, taskTemplateId: "standard-8", isNewlyAdded: false, title: "Dashboard LintasArta DM", project: "DM", detail: "Perhatikan all device quota / over quota usage; eskalasi langsung jika setelah pukul 01.00 data masih kosong.", state: "repeat", completed: true },
  { id: 9, taskTemplateId: "standard-9", isNewlyAdded: true, title: "Perhitungan volume output data APH", project: "APH", detail: "Rekap output GGSN Ericsson, Huawei, ZTE dan UFP Huawei 5GC dalam volume serta events per hari.", state: "waiting", completed: false },
  { id: 10, taskTemplateId: "standard-10", isNewlyAdded: true, title: "Report SM MonthlyHealth-SMMB", project: "SM", detail: "Pengerjaan materi Presentation MonthlyHealth-SMMB masih berlangsung.", state: "in-progress", completed: false },
];

export const STANDARD_MONITORED_PROJECTS = [
  "B2B",
  "DM",
  "EPC",
  "APH",
  "SM",
  "ActiveMQ",
  "USIEM",
  "MB",
  "UNEM",
  "L2",
  "SM/ActiveMQ",
];

export const initialHandoverRecord: HandoverRecordData = {
  sourceShift: "Subuh",
  targetShift: "Pagi",
  sourcePic: "Agnes",
  targetPic: "Galih, Natanael, Pangondion",
  monitoringSummary: "Pengecekan dan monitoring telah dilakukan serta dilaporkan di grup Telegram sesuai checkpoint yang ditentukan.",
  monitoringOwner: "Agnes",
  monitoredProjects: [...STANDARD_MONITORED_PROJECTS],
  validationNote: "Galih, Natanael, dan Pangondion telah memeriksa hasil monitoring pada sesi handover.",
  notes: "Semua checkpoint monitoring subuh telah dilaporkan ke Telegram. Perhatikan penanganan tiket incident USIEM yang masih dalam investigasi oleh tim DevOps.",
  findings: [
    {
      project: "USIEM",
      title: "Log direct MSS belum tampil",
      detail: "Log MSS Eric dan MSS Nokia sempat tertumpuk pada log distributor. Layanan telah di-restart dan tren penumpukan mulai menurun.",
      state: "waiting",
    },
    {
      project: "USIEM",
      title: "Input Graylog tidak menerima data",
      detail: "Input siem-fw-diameter-event, siem-fw-ss7-event, dan siem-fw-gtp-event tidak menerima data; sedang ditindaklanjuti di grup USIEM DevOps.",
      state: "in-progress",
    },
  ],
  monitoringCheckpoints: [
    { time: "07:00", project: "B2B", task: "Health check gateway B2B & failover", verdict: "ok", note: "Response time normal < 180ms" },
    { time: "07:15", project: "SM", task: "Queue distributor check", verdict: "ok", note: "Trafik antrian stabil" },
    { time: "07:30", project: "USIEM", task: "Log collector audit", verdict: "nok", note: "Log direct MSS sempat tertumpuk" },
    { time: "07:45", project: "DM", task: "Database sync check", verdict: "ok", note: "Replika in sync" },
    { time: "08:00", project: "ActiveMQ", task: "Broker heap & consumer count", verdict: "ok", note: "Heap 42%, normal" },
  ],
  tasks: initialHandoverTasks,
};

export const teamMembers = [
  { name: "Mhd. Galih Khairi", role: "Koordinator" },
  { name: "Kristina Marbun", role: "Operator" },
  { name: "M. Ihsanul Arifin", role: "Operator" },
];

export const projectHealthWeekly = [
  { project: "SM", days: [96, 94, 92, 98, 95, 90, 93] },
  { project: "B2B", days: [97, 95, 99, 94, 92, 96, 91] },
  { project: "USIEM", days: [100, 99, 100, 98, 100, 99, 100] },
  { project: "MB", days: [100, 100, 98, 100, 99, 100, 100] },
  { project: "EPC Tools", days: [99, 100, 100, 97, 100, 100, 99] },
  { project: "DM", days: [98, 100, 99, 100, 97, 100, 100] },
  { project: "UNEM", days: [100, 98, 100, 100, 99, 100, 100] },
];

export function toDateInputValue(date = new Date()) {
  const timezoneOffset = date.getTimezoneOffset() * 60000;
  return new Date(date.getTime() - timezoneOffset).toISOString().slice(0, 10);
}

export function formatHandoverDate(value: string) {
  const parsed = new Date(`${value}T00:00:00`);
  return Number.isNaN(parsed.getTime())
    ? value
    : new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "long", year: "numeric" }).format(parsed);
}

export function nowClockLabel() {
  const now = new Date();
  return `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
}

export function makeTicketId() {
  return `86d4${Math.random().toString(36).slice(2, 7)}`;
}

export function createHandoverDraft(
  record: HandoverRecordData = initialHandoverRecord,
  date = toDateInputValue(),
): HandoverDraft {
  return {
    date,
    sourceShift: record.sourceShift,
    targetShift: record.targetShift,
    sourcePic: record.sourcePic,
    targetPic: record.targetPic,
    monitoringOwner: record.monitoringOwner,
    monitoredProjects: record.monitoredProjects.join(", "),
    monitoringSummary: record.monitoringSummary,
    validationNote: record.validationNote,
    notes: record.notes ?? "",
    findings: record.findings.map((finding) => ({ ...finding })),
    tasks: record.tasks.map((task) => ({ ...task })),
    openTickets: record.openTickets ? record.openTickets.map((t) => ({ ...t })) : [],
    closedTickets: record.closedTickets ? record.closedTickets.map((t) => ({ ...t })) : [],
    receiverEmail: record.receiverEmail ?? "",
    monitoringExceptions: (record.monitoringExceptions ?? []).map((item) => ({ ...item })),
  };
}

export function createShiftHandoverDraft(date = new Date()): HandoverDraft {
  const draft = createHandoverDraft(initialHandoverRecord, toDateInputValue(date));

  // Reuse task instructions, not another shift's PICs or acceptance state.
  return {
    ...draft,
    sourceShift: getShiftInfo(date).shortLabel,
    targetShift: getShiftInfo(getNextShiftChange(date)).shortLabel,
    sourcePic: "",
    targetPic: "",
    monitoringOwner: "",
    monitoredProjects: STANDARD_MONITORED_PROJECTS.join(", "),
    monitoringSummary: "",
    validationNote: "",
    notes: "",
    findings: [],
    tasks: draft.tasks.map((task) => ({ ...task, completed: false })),
  };
}

export function initials(name: string | null | undefined) {
  if (!name?.trim()) return "??";
  return name
    .trim()
    .split(/\s+/)
    .map((part) => part[0] ?? "")
    .join("")
    .slice(0, 2)
    .toUpperCase() || "??";
}

/**
 * Canonical check for whether a ticket is considered "open" (in-progress).
 * Unifies the fragmented status checks scattered across the codebase.
 */
export function isOpenTicket(ticket: Ticket): boolean {
  const s = ticket.status.toLowerCase();
  return (
    s === "active" ||
    s === "aktivitas" ||
    s === "activity" ||
    s === "open" ||
    s === "pending" ||
    s === "menunggu" ||
    s === "escalated" ||
    s === "eskalasi" ||
    s === "re-open"
  );
}

/** Safe average that returns 0 for empty arrays instead of NaN. */
export function safeAverage(values: number[]): number {
  if (!values.length) return 0;
  return Math.round(values.reduce((sum, v) => sum + v, 0) / values.length);
}

// ── Dynamic date utilities (replaces hardcoded "2026-08-31" etc.) ──

/** Returns today's date in YYYY-MM-DD format, pinned to WIB (UTC+7). */
export function getTodayWIB(): string {
  const now = new Date();
  // Convert to WIB by adding UTC+7 offset
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs);
  return wib.toISOString().slice(0, 10);
}

/** Returns yesterday's date in YYYY-MM-DD, pinned to WIB. */
export function getYesterdayWIB(): string {
  const now = new Date();
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs - 86_400_000);
  return wib.toISOString().slice(0, 10);
}

/** Returns start of current ISO week (Monday) in YYYY-MM-DD, pinned to WIB. */
export function getStartOfWeekWIB(): string {
  const now = new Date();
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs);
  const day = wib.getDay(); // 0=Sun
  const diff = day === 0 ? 6 : day - 1; // Monday=0
  wib.setDate(wib.getDate() - diff);
  return wib.toISOString().slice(0, 10);
}

/** Returns start of current month in YYYY-MM-DD, pinned to WIB. */
export function getStartOfMonthWIB(): string {
  const today = getTodayWIB();
  return today.slice(0, 8) + "01";
}

/** Returns start of previous ISO week (Monday) in YYYY-MM-DD. */
export function getStartOfLastWeekWIB(): string {
  const now = new Date();
  const wibMs = now.getTime() + (7 * 60 + now.getTimezoneOffset()) * 60_000;
  const wib = new Date(wibMs);
  const day = wib.getDay();
  const diff = day === 0 ? 6 : day - 1;
  wib.setDate(wib.getDate() - diff - 7);
  return wib.toISOString().slice(0, 10);
}

/** Returns end of previous ISO week (Sunday) in YYYY-MM-DD. */
export function getEndOfLastWeekWIB(): string {
  const start = getStartOfLastWeekWIB();
  const d = new Date(start + "T00:00:00");
  d.setDate(d.getDate() + 6);
  return d.toISOString().slice(0, 10);
}

/** Returns YYYY-MM prefix for last month, pinned to WIB. */
export function getLastMonthPrefixWIB(): string {
  const today = getTodayWIB();
  const y = parseInt(today.slice(0, 4), 10);
  const m = parseInt(today.slice(5, 7), 10);
  const prevMonth = m === 1 ? 12 : m - 1;
  const prevYear = m === 1 ? y - 1 : y;
  return `${prevYear}-${String(prevMonth).padStart(2, "0")}`;
}

export const seedRosterMembers: RosterMember[] = [
  {
    id: "mem-1",
    name: "Galih Khairi",
    role: "Operator NOC",
    employeeId: "EMP-1048",
    email: "galih.khairi@company.id",
    phone: "+62 812-3456-7890",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "15 Jan 2024",
    avatarBg: "#2563eb",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 98.5,
      shiftsCompleted: 142,
      handoverScore: 99.2,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present", note: "On-time check-in, lead NOC console" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present", note: "Handover smoothly confirmed" },
      { date: "26 Aug", shift: "Shift Malam", status: "Present" },
      { date: "25 Aug", shift: "Shift Malam", status: "Present" },
      { date: "24 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-2",
    name: "Pangondion Kurniawan",
    role: "Shift Lead",
    employeeId: "EMP-1012",
    email: "pangondion.k@company.id",
    phone: "+62 813-8877-6655",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "01 Mar 2023",
    avatarBg: "#7c3aed",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 100,
      shiftsCompleted: 218,
      handoverScore: 99.8,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present", note: "Shift supervisor & escalation handler" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present" },
      { date: "26 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-3",
    name: "Kurnia Meidiyansyah",
    role: "Operator NOC",
    employeeId: "EMP-1055",
    email: "kurnia.m@company.id",
    phone: "+62 819-9011-2233",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "10 Feb 2024",
    avatarBg: "#059669",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 96.8,
      shiftsCompleted: 110,
      handoverScore: 97.5,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-4",
    name: "Muhammad Iqbal",
    role: "L2 Specialist",
    employeeId: "EMP-1029",
    email: "m.iqbal@company.id",
    phone: "+62 856-1122-3344",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "On Break",
    joinDate: "20 Jun 2023",
    avatarBg: "#d97706",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 97.0,
      shiftsCompleted: 165,
      handoverScore: 98.4,
    },
    history: [
      { date: "28 Aug", shift: "Shift Malam", status: "Present", note: "Break scheduled 19:30–20:15" },
      { date: "27 Aug", shift: "Shift Malam", status: "Present" },
    ],
  },
  {
    id: "mem-5",
    name: "Sarah Wijaya",
    role: "Incident Coordinator",
    employeeId: "EMP-1008",
    email: "sarah.w@company.id",
    phone: "+62 811-2233-4455",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "12 Oct 2022",
    avatarBg: "#db2777",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 99.1,
      shiftsCompleted: 240,
      handoverScore: 99.5,
    },
    history: [
      { date: "28 Aug", shift: "Shift Pagi", status: "Present", note: "Incident bridge commander" },
    ],
  },
  {
    id: "mem-6",
    name: "Bagas Pratama",
    role: "Operator NOC",
    employeeId: "EMP-1062",
    email: "bagas.p@company.id",
    phone: "+62 817-4455-6677",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "05 May 2024",
    avatarBg: "#4f46e5",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 95.0,
      shiftsCompleted: 88,
      handoverScore: 96.0,
    },
    history: [
      { date: "28 Aug", shift: "Shift Subuh", status: "Present", note: "Early morning batch and monitoring checks" },
    ],
  },
  {
    id: "mem-7",
    name: "Dimas Anggoro",
    role: "Infrastructure Engineer",
    employeeId: "EMP-1033",
    email: "dimas.a@company.id",
    phone: "+62 821-3344-5566",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Off Duty",
    joinDate: "18 Aug 2023",
    avatarBg: "#0891b2",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 98.0,
      shiftsCompleted: 175,
      handoverScore: 98.9,
    },
    history: [
      { date: "28 Aug", shift: "Shift Pagi", status: "Present", note: "Completed morning DC routine" },
    ],
  },
  {
    id: "mem-8",
    name: "Annisa Rahmawati",
    role: "Operator NOC",
    employeeId: "EMP-1070",
    email: "annisa.r@company.id",
    phone: "+62 857-7788-9900",
    currentShift: "Cuti Tahunan (On Leave)",
    status: "On Leave",
    joinDate: "01 Jul 2024",
    avatarBg: "#ea580c",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sel", date: "25 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Rab", date: "26 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Kam", date: "27 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Jum", date: "28 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: {
      onTimePercentage: 96.0,
      shiftsCompleted: 45,
      handoverScore: 97.0,
    },
    history: [
      { date: "28 Aug", shift: "Annual Leave", status: "Leave", note: "Approved annual leave" },
    ],
  },
  {
    id: "mem-9",
    name: "Rizky Ramadhani",
    role: "Operator NOC",
    employeeId: "EMP-1072",
    email: "rizky.r@company.id",
    phone: "+62 812-7711-2233",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "15 Aug 2024",
    avatarBg: "#0284c7",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 97.5, shiftsCompleted: 62, handoverScore: 98.1 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-10",
    name: "Fajar Nugroho",
    role: "Incident Coordinator",
    employeeId: "EMP-1015",
    email: "fajar.n@company.id",
    phone: "+62 813-9988-7766",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "04 Jan 2023",
    avatarBg: "#8b5cf6",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 99.4, shiftsCompleted: 210, handoverScore: 99.7 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-11",
    name: "Dewi Sartika",
    role: "Operator NOC",
    employeeId: "EMP-1065",
    email: "dewi.s@company.id",
    phone: "+62 818-2233-4455",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "10 Jun 2024",
    avatarBg: "#ec4899",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 96.2, shiftsCompleted: 78, handoverScore: 96.9 },
    history: [{ date: "28 Aug", shift: "Shift Subuh", status: "Present" }],
  },
  {
    id: "mem-12",
    name: "Budi Santoso",
    role: "Shift Lead",
    employeeId: "EMP-1009",
    email: "budi.s@company.id",
    phone: "+62 811-3344-5566",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "12 Nov 2022",
    avatarBg: "#10b981",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 99.0, shiftsCompleted: 235, handoverScore: 99.4 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-13",
    name: "Maya Indira",
    role: "L2 Specialist",
    employeeId: "EMP-1031",
    email: "maya.i@company.id",
    phone: "+62 856-7788-9911",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "18 Sep 2023",
    avatarBg: "#6366f1",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 98.2, shiftsCompleted: 155, handoverScore: 98.7 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-14",
    name: "Dwi Cahyono",
    role: "Operator NOC",
    employeeId: "EMP-1068",
    email: "dwi.c@company.id",
    phone: "+62 817-6677-8899",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "20 May 2024",
    avatarBg: "#14b8a6",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 95.8, shiftsCompleted: 92, handoverScore: 96.5 },
    history: [{ date: "28 Aug", shift: "Shift Subuh", status: "Present" }],
  },
  {
    id: "mem-15",
    name: "Reza Pratama",
    role: "Infrastructure Engineer",
    employeeId: "EMP-1038",
    email: "reza.p@company.id",
    phone: "+62 822-1122-3344",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "Active",
    joinDate: "05 Dec 2023",
    avatarBg: "#f59e0b",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 98.8, shiftsCompleted: 140, handoverScore: 99.1 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-16",
    name: "Eka Putri",
    role: "Operator NOC",
    employeeId: "EMP-1059",
    email: "eka.p@company.id",
    phone: "+62 819-4455-6677",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "15 Mar 2024",
    avatarBg: "#a855f7",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 97.2, shiftsCompleted: 104, handoverScore: 97.8 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-17",
    name: "Hendra Wijaya",
    role: "Incident Coordinator",
    employeeId: "EMP-1018",
    email: "hendra.w@company.id",
    phone: "+62 812-8899-0011",
    currentShift: "Shift Subuh (00:00–08:30 WIB)",
    status: "Off Duty",
    joinDate: "01 Feb 2023",
    avatarBg: "#ef4444",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sel", date: "25 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Rab", date: "26 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Kam", date: "27 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Jum", date: "28 Aug", shift: "Subuh", hours: "00:00–08:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 99.2, shiftsCompleted: 198, handoverScore: 99.3 },
    history: [{ date: "28 Aug", shift: "Shift Subuh", status: "Present" }],
  },
  {
    id: "mem-18",
    name: "Tiara Andini",
    role: "Operator NOC",
    employeeId: "EMP-1077",
    email: "tiara.a@company.id",
    phone: "+62 858-1122-3344",
    currentShift: "Shift Malam (16:00–00:30 WIB)",
    status: "On Break",
    joinDate: "01 Sep 2024",
    avatarBg: "#06b6d4",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sel", date: "25 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Rab", date: "26 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Kam", date: "27 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Jum", date: "28 Aug", shift: "Malam", hours: "16:00–00:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 96.5, shiftsCompleted: 42, handoverScore: 97.2 },
    history: [{ date: "28 Aug", shift: "Shift Malam", status: "Present" }],
  },
  {
    id: "mem-19",
    name: "Aditya Pratama",
    role: "L2 Specialist",
    employeeId: "EMP-1035",
    email: "aditya.p@company.id",
    phone: "+62 813-5566-7788",
    currentShift: "Shift Pagi (08:00–16:30 WIB)",
    status: "Active",
    joinDate: "14 Oct 2023",
    avatarBg: "#3b82f6",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sel", date: "25 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Rab", date: "26 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Kam", date: "27 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Jum", date: "28 Aug", shift: "Pagi", hours: "08:00–16:30" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 98.6, shiftsCompleted: 172, handoverScore: 98.9 },
    history: [{ date: "28 Aug", shift: "Shift Pagi", status: "Present" }],
  },
  {
    id: "mem-20",
    name: "Nadia Safitri",
    role: "Operator NOC",
    employeeId: "EMP-1082",
    email: "nadia.s@company.id",
    phone: "+62 878-9900-1122",
    currentShift: "Cuti Tahunan (On Leave)",
    status: "On Leave",
    joinDate: "20 Jul 2024",
    avatarBg: "#f97316",
    weeklySchedule: [
      { day: "Sen", date: "24 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sel", date: "25 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Rab", date: "26 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Kam", date: "27 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Jum", date: "28 Aug", shift: "Leave", hours: "Cuti" },
      { day: "Sab", date: "29 Aug", shift: "Off", hours: "Libur" },
      { day: "Min", date: "30 Aug", shift: "Off", hours: "Libur" },
    ],
    stats: { onTimePercentage: 95.5, shiftsCompleted: 38, handoverScore: 96.0 },
    history: [{ date: "28 Aug", shift: "Annual Leave", status: "Leave" }],
  },
];

export const seedSwapRequests: ShiftSwapRequest[] = [
  {
    id: "swap-1",
    requesterId: "mem-6",
    requesterName: "Bagas Pratama",
    targetMemberId: "mem-3",
    targetMemberName: "Kurnia Meidiyansyah",
    requestedDate: "29 Aug 2026",
    currentShift: "Shift Malam (16:00–00:30)",
    targetShift: "Shift Pagi (08:00–16:30)",
    reason: "Ada keperluan keluarga mendesak di pagi hari.",
    status: "Pending",
    createdAt: "28 Aug 18:40",
  },
  {
    id: "swap-2",
    requesterId: "mem-1",
    requesterName: "Galih Khairi",
    targetMemberId: "mem-7",
    targetMemberName: "Dimas Anggoro",
    requestedDate: "22 Aug 2026",
    currentShift: "Shift Pagi",
    targetShift: "Shift Malam",
    reason: "Penyesuaian jadwal maintenance datacenter.",
    status: "Approved",
    createdAt: "21 Aug 10:15",
  },
];
