import type {
  SopEntry,
  CredentialEntry,
  QuickLink,
  EscalationContact,
} from "./types";

/* ═══════════════════════════════════════════════
   SEED DATA — SOP & PROSEDUR
═══════════════════════════════════════════════ */

export const seedSopEntries: SopEntry[] = [
  {
    id: "sop-001",
    title: "SOP Penanganan Incident Priority 1 (Critical)",
    category: "Incident",
    project: "All",
    description:
      "Prosedur standar untuk menangani incident dengan prioritas tertinggi (P1/Critical) yang berdampak langsung pada layanan produksi.",
    steps: [
      { order: 1, instruction: "Identifikasi dan validasi incident: cek alert Grafana/Zabbix, konfirmasi dampak pada service." },
      { order: 2, instruction: "Buat tiket incident di ITSM Portal dengan severity Critical. Catat waktu deteksi (T0)." },
      { order: 3, instruction: "Kirim notifikasi awal ke grup Telegram/Teams NOC dalam 5 menit pertama." },
      { order: 4, instruction: "Eskalasi ke L2 Specialist jika belum resolved dalam 15 menit (lihat Kontak Eskalasi)." },
      { order: 5, instruction: "Dokumentasikan timeline kejadian: T0 (deteksi), T1 (notifikasi), T2 (eskalasi), T3 (resolved)." },
      { order: 6, instruction: "Buat Root Cause Analysis (RCA) report dalam 24 jam setelah incident resolved." },
    ],
    attachments: [
      {
        id: "att-001-1",
        title: "SOP-P1-Incident-Response.pdf",
        url: "https://drive.internal.tritronik.com/sop/SOP-P1-Incident-Response-v2.pdf",
        type: "pdf",
        format: "PDF Document (2.4 MB)",
        description: "Dokumen SOP resmi ditandatangani VP Tech Ops & Incident Manager",
      },
      {
        id: "att-001-2",
        title: "Template-RCA-Insiden-Major.docx",
        url: "https://docs.google.com/document/d/1A2B3C4D5E/edit?usp=sharing",
        type: "word",
        format: "Word / Google Docs",
        description: "Template standar Root Cause Analysis (5-Whys & Action Items)",
      },
      {
        id: "att-001-3",
        title: "Video-Simulasi-Eskalasi-P1-Bridge.mp4",
        url: "https://stream.internal.tritronik.com/training/p1-simulation-walkthrough.mp4",
        type: "video",
        format: "Video Recording (24 min)",
        description: "Rekaman simulasi call bridge, eskalasi L2/L3, dan pengisian timeline",
      },
      {
        id: "att-001-4",
        title: "Monthly-Incident-Summary-Agustus-2026.xlsx",
        url: "https://sharepoint.tritronik.com/reports/2026/Monthly-Incident-Report-Aug.xlsx",
        type: "report",
        format: "Monthly Report (Excel)",
        description: "Laporan rekap bulanan MTTA/MTTR, SLA compliance, & repeat issues",
      },
    ],
    externalLinks: [
      { label: "Template RCA Report", url: "https://docs.google.com/templates/rca" },
      { label: "Panduan Severity Matrix", url: "https://confluence.internal/severity-matrix" },
    ],
    updatedAt: "2026-09-25",
    updatedBy: "Galih Khairi",
  },
  {
    id: "sop-002",
    title: "SOP Monitoring Harian — Checklist Shift",
    category: "Monitoring",
    project: "All",
    description:
      "Panduan langkah-langkah monitoring rutin yang harus dilakukan setiap jam oleh operator NOC selama shift berjalan.",
    steps: [
      { order: 1, instruction: "Login ke semua dashboard monitoring (Grafana, Zabbix, Graylog SIEM)." },
      { order: 2, instruction: "Cek status semua layanan pada halaman Monitoring Sekarang di Central Dashboard." },
      { order: 3, instruction: "Periksa alert aktif dan triage: Critical → segera tangani, Warning → catat dan monitor." },
      { order: 4, instruction: "Validasi checkpoint sesuai jadwal: beri penilaian OK / NOK + catatan jika perlu." },
      { order: 5, instruction: "Catat temuan anomali di catatan shift untuk diteruskan saat handover." },
      { order: 6, instruction: "Jika NOK: isi formulir Not Adequate dengan detail masalah dan action plan." },
    ],
    attachments: [
      {
        id: "att-002-1",
        title: "Checklist-Monitoring-Shift-NOC.pdf",
        url: "https://drive.internal.tritronik.com/sop/Checklist-Monitoring-Hourly-2026.pdf",
        type: "pdf",
        format: "PDF Guide (1.1 MB)",
        description: "Lembar panduan verifikasi hourly checkpoint dan parameter threshold",
      },
      {
        id: "att-002-2",
        title: "Video-Tutorial-Triage-Graylog-SIEM.mp4",
        url: "https://stream.internal.tritronik.com/training/graylog-siem-triage-guide.mp4",
        type: "video",
        format: "Video Tutorial (18 min)",
        description: "Video tutorial pencarian log stream, triage anomali, dan query regex",
      },
      {
        id: "att-002-3",
        title: "Monthly-Monitoring-Health-KPI-2026.xlsx",
        url: "https://sharepoint.tritronik.com/reports/2026/Monthly-Service-Health-KPI.xlsx",
        type: "report",
        format: "Monthly Report",
        description: "Laporan evaluasi performa layanan bulanan dan rasio OK/NOK",
      },
    ],
    updatedAt: "2026-09-28",
    updatedBy: "Galih Khairi",
  },
  {
    id: "sop-003",
    title: "SOP Handover Shift",
    category: "Handover",
    description:
      "Prosedur serah terima shift untuk memastikan continuity operasional antara shift yang keluar dan shift yang masuk.",
    steps: [
      { order: 1, instruction: "Buka halaman Shift Log dan klik 'Siapkan Handover' minimal 30 menit sebelum shift berakhir." },
      { order: 2, instruction: "Isi semua field wajib: ringkasan monitoring, temuan, dan open ticket yang masih aktif." },
      { order: 3, instruction: "Review daftar task handover — tandai yang sudah selesai, tambahkan yang baru jika ada." },
      { order: 4, instruction: "Kirim handover ke shift penerima dan tunggu konfirmasi acceptance." },
      { order: 5, instruction: "Shift penerima wajib membaca dan meng-accept handover dalam 15 menit pertama shift." },
    ],
    attachments: [
      {
        id: "att-003-1",
        title: "Format-Standard-Handover-Log.docx",
        url: "https://docs.google.com/document/d/handover-standard-template/edit",
        type: "word",
        format: "Word Document",
        description: "Format standar resume serah terima tugas dan catatan tiket terbuka",
      },
      {
        id: "att-003-2",
        title: "Rekap-Handover-Audit-Monthly.xlsx",
        url: "https://sharepoint.tritronik.com/reports/2026/Handover-Quality-Audit.xlsx",
        type: "report",
        format: "Monthly Report",
        description: "Laporan audit kedisiplinan dan kelengkapan serah terima shift bulanan",
      },
    ],
    updatedAt: "2026-09-20",
    updatedBy: "Kristina Marbun",
  },
  {
    id: "sop-004",
    title: "SOP Pengecekan Queue ActiveMQ",
    category: "Monitoring",
    project: "SM/ActiveMQ",
    description:
      "Langkah pengecekan kesehatan queue ActiveMQ pada server SM (smng109) dan tindakan yang harus diambil jika terjadi penumpukan.",
    steps: [
      { order: 1, instruction: "Akses web console ActiveMQ di URL yang tersedia di tab Link & Tools." },
      { order: 2, instruction: "Navigasi ke Queues → cek jumlah Pending Messages pada queue `fulldecode.smng109`." },
      { order: 3, instruction: "Jika Pending > 1000: catat sebagai NOK, screenshot dan kirim ke grup Teams." },
      { order: 4, instruction: "Jika Pending > 5000: eskalasi ke L2 Specialist SM (lihat Kontak Eskalasi)." },
      { order: 5, instruction: "Cek Consumer Count — jika 0 berarti consumer mati, eskalasi segera ke L2." },
      { order: 6, instruction: "Dokumentasikan di checkpoint monitoring dengan screenshot grafik queue." },
    ],
    attachments: [
      {
        id: "att-004-1",
        title: "Panduan-Recovery-ActiveMQ-Queue.pdf",
        url: "https://drive.internal.tritronik.com/sop/ActiveMQ-Queue-Troubleshooting.pdf",
        type: "pdf",
        format: "PDF Document",
        description: "Langkah detail penanganan antrian menumpuk dan purge DLQ aman",
      },
      {
        id: "att-004-2",
        title: "Video-Step-By-Step-ActiveMQ-Inspection.mp4",
        url: "https://stream.internal.tritronik.com/training/activemq-queue-inspection.mp4",
        type: "video",
        format: "Video SOP (12 min)",
        description: "Video teknis pengecekan consumer count dan alert trigger via CLI",
      },
    ],
    externalLinks: [
      { label: "ActiveMQ Web Console", url: "https://activemq.internal:8161/admin/queues.jsp" },
    ],
    updatedAt: "2026-09-18",
    updatedBy: "Muhammad Ihsanul Arifin",
  },
  {
    id: "sop-005",
    title: "SOP Pengecekan Kafka Topic (B2B)",
    category: "Monitoring",
    project: "B2B",
    description:
      "Prosedur pemeriksaan health Kafka topics pada project B2B, termasuk verifikasi producer/consumer lag dan disk usage.",
    steps: [
      { order: 1, instruction: "Akses Kafka UI / Confluent Control Center melalui link di tab Link & Tools." },
      { order: 2, instruction: "Cek overview: jumlah topic aktif, partisi, dan broker health." },
      { order: 3, instruction: "Periksa consumer lag: jika lag > 10.000 pada consumer group utama, catat sebagai NOK." },
      { order: 4, instruction: "Cek disk usage server B2B (`/apps pv-bbsvsoe1`): threshold warning 80%, critical 90%." },
      { order: 5, instruction: "Verifikasi aliran pesan pada topik b2b-fullprov: harus ada traffic dalam 1 jam terakhir." },
    ],
    attachments: [
      {
        id: "att-005-1",
        title: "Kafka-B2B-Cluster-Topology.pdf",
        url: "https://drive.internal.tritronik.com/sop/Kafka-B2B-Cluster-Architecture.pdf",
        type: "pdf",
        format: "PDF Topology",
        description: "Diagram arsitektur cluster Kafka B2B, broker mapping, dan topic partitions",
      },
      {
        id: "att-005-2",
        title: "Monthly-Throughput-B2B-Lag-Report.xlsx",
        url: "https://sharepoint.tritronik.com/reports/2026/B2B-Kafka-Throughput-Report.xlsx",
        type: "report",
        format: "Monthly Report",
        description: "Laporan bulanan volume transaksi provisi B2B dan analisis lag puncak",
      },
    ],
    updatedAt: "2026-09-22",
    updatedBy: "Muhammad Ihsanul Arifin",
  },
  {
    id: "sop-006",
    title: "SOP Pengecekan Graylog & SIEM",
    category: "Monitoring",
    project: "USIEM",
    description:
      "Prosedur verifikasi kesehatan Graylog SIEM, termasuk input stream, indeks, dan alert rules.",
    steps: [
      { order: 1, instruction: "Login ke Graylog SIEM via URL di Link & Tools." },
      { order: 2, instruction: "Cek System → Overview: pastikan semua input dalam status RUNNING." },
      { order: 3, instruction: "Periksa throughput: minimal 100 msg/s pada input utama. Di bawah itu = anomali." },
      { order: 4, instruction: "Cek index rotation: pastikan index terbaru tidak lebih dari 1 jam yang lalu." },
      { order: 5, instruction: "Review triggered alerts dalam 1 jam terakhir — eskalasi jika ada critical alert." },
    ],
    attachments: [
      {
        id: "att-006-1",
        title: "SIEM-Alert-Rule-Playbook.pdf",
        url: "https://drive.internal.tritronik.com/sop/SIEM-Alert-Rule-Playbook.pdf",
        type: "pdf",
        format: "PDF Document",
        description: "Daftar rule deteksi anomali keamanan dan panduan tindakan awal L1",
      },
    ],
    updatedAt: "2026-09-15",
    updatedBy: "Agnes Siahaan",
  },
  {
    id: "sop-007",
    title: "SOP Maintenance Window",
    category: "Maintenance",
    description:
      "Prosedur pelaksanaan maintenance terjadwal, termasuk koordinasi dengan tim terkait dan komunikasi ke stakeholder.",
    steps: [
      { order: 1, instruction: "Verifikasi jadwal maintenance di calendar dan Change Request yang sudah di-approve." },
      { order: 2, instruction: "Kirim notifikasi T-30 menit ke semua stakeholder via email dan Teams." },
      { order: 3, instruction: "Backup konfigurasi dan state sebelum maintenance dimulai." },
      { order: 4, instruction: "Eksekusi maintenance sesuai runbook yang sudah disetujui." },
      { order: 5, instruction: "Post-maintenance: verifikasi semua service kembali normal dalam 15 menit." },
      { order: 6, instruction: "Kirim notifikasi completion dan update tiket maintenance di ITSM." },
    ],
    attachments: [
      {
        id: "att-007-1",
        title: "Maintenance-Window-Checklist-Template.docx",
        url: "https://docs.google.com/document/d/maintenance-window-checklist/edit",
        type: "word",
        format: "Word Template",
        description: "Template checklist verifikasi pra-maintenance dan pasca-maintenance",
      },
      {
        id: "att-007-2",
        title: "Laporan-Bulanan-Change-Execution.xlsx",
        url: "https://sharepoint.tritronik.com/reports/2026/Monthly-Change-Execution-Report.xlsx",
        type: "report",
        format: "Monthly Report",
        description: "Rekapitulasi pelaksanaan maintenance window dan tingkat keberhasilan",
      },
    ],
    updatedAt: "2026-09-10",
    updatedBy: "Galih Khairi",
  },
];

/* ═══════════════════════════════════════════════
   SEED DATA — AKSES & KREDENSIAL
═══════════════════════════════════════════════ */

export const seedCredentials: CredentialEntry[] = [
  {
    id: "cred-001",
    label: "Grafana Dashboard (Produksi)",
    category: "Website",
    project: "All",
    url: "https://grafana.internal.tritronik.com",
    username: "noc-operator",
    password: "change-me",
    notes: "Akses read-only untuk monitoring. Jangan ubah dashboard.",
  },
  {
    id: "cred-002",
    label: "Zabbix Monitoring",
    category: "Website",
    project: "All",
    url: "https://zabbix.internal.tritronik.com",
    username: "noc-viewer",
    password: "change-me",
    notes: "Role: Viewer. Untuk melihat host status dan triggers.",
  },
  {
    id: "cred-003",
    label: "Graylog SIEM",
    category: "Website",
    project: "USIEM",
    url: "https://graylog.siem.tritronik.com",
    username: "operator-siem",
    password: "change-me",
    notes: "Akses ke stream SIEM dan search. Alert management hanya L2+.",
  },
  {
    id: "cred-004",
    label: "VPN FortiClient — Akses Data Center",
    category: "VPN",
    host: "vpn.tritronik.com",
    port: "443",
    protocol: "SSL-VPN",
    username: "noc-vpn-team",
    password: "change-me",
    notes: "Profile: NOC-DC-Access. Gunakan FortiClient v7.2+.",
  },
  {
    id: "cred-005",
    label: "VPN WireGuard — Remote NOC",
    category: "VPN",
    host: "wg.tritronik.com",
    port: "51820",
    protocol: "WireGuard",
    username: "noc-wg-01",
    password: "change-me",
    notes: "Config file tersedia di Share Drive NOC. Minta ke Shift Lead jika belum punya.",
  },
  {
    id: "cred-006",
    label: "SSH Server B2B (pv-bbsvsoe1)",
    category: "SSH",
    project: "B2B",
    host: "10.10.20.15",
    port: "22",
    username: "noc-b2b",
    password: "change-me",
    notes: "Akses untuk cek disk usage dan Kafka logs. Jangan restart service tanpa approval L2.",
  },
  {
    id: "cred-007",
    label: "SSH Server SM (smng109)",
    category: "SSH",
    project: "SM/ActiveMQ",
    host: "10.10.20.30",
    port: "22",
    username: "noc-sm",
    password: "change-me",
    notes: "Untuk cek ActiveMQ logs dan queue status via CLI.",
  },
  {
    id: "cred-008",
    label: "ITSM Ticketing Portal",
    category: "Website",
    url: "https://itsm.tritronik.com",
    username: "noc-operator",
    password: "change-me",
    notes: "Untuk membuat dan manage tiket incident/request.",
  },
  {
    id: "cred-009",
    label: "API Key — Monitoring Webhook",
    category: "API",
    project: "All",
    username: "webhook-noc",
    password: "change-me",
    notes: "API key untuk integrasi webhook alert ke Teams/Telegram. Jangan share ke external.",
    expiresAt: "2027-03-31",
  },
];

/* ═══════════════════════════════════════════════
   SEED DATA — LINK & TOOLS
═══════════════════════════════════════════════ */

export const seedQuickLinks: QuickLink[] = [
  {
    id: "link-001",
    label: "Grafana Dashboard",
    url: "https://grafana.internal.tritronik.com",
    category: "Dashboard",
    project: "All",
    description: "Dashboard utama monitoring semua project — CPU, memory, uptime, traffic.",
    icon: "activity",
  },
  {
    id: "link-002",
    label: "Zabbix Monitoring",
    url: "https://zabbix.internal.tritronik.com",
    category: "Dashboard",
    project: "All",
    description: "Host monitoring, trigger alerts, dan network maps.",
    icon: "bar-chart",
  },
  {
    id: "link-003",
    label: "Graylog SIEM",
    url: "https://graylog.siem.tritronik.com",
    category: "Dashboard",
    project: "USIEM",
    description: "Log management & SIEM — search, stream, dan alert.",
    icon: "search",
  },
  {
    id: "link-004",
    label: "ITSM Portal",
    url: "https://itsm.tritronik.com",
    category: "Ticketing",
    description: "Buat dan kelola tiket incident, request, dan change.",
    icon: "ticket",
  },
  {
    id: "link-005",
    label: "Kafka UI (B2B)",
    url: "https://kafka-ui.internal.tritronik.com",
    category: "Dashboard",
    project: "B2B",
    description: "Kafka topic browser — consumer groups, messages, partitions.",
    icon: "radio",
  },
  {
    id: "link-006",
    label: "ActiveMQ Console (SM)",
    url: "https://activemq.internal:8161/admin",
    category: "Dashboard",
    project: "SM/ActiveMQ",
    description: "Queue management — pending messages, consumers, DLQ.",
    icon: "layers",
  },
  {
    id: "link-007",
    label: "Confluence Wiki",
    url: "https://confluence.tritronik.com",
    category: "Internal",
    description: "Dokumentasi teknis, architecture diagrams, dan meeting notes.",
    icon: "book-open",
  },
  {
    id: "link-008",
    label: "Microsoft Teams — NOC Channel",
    url: "https://teams.microsoft.com/l/channel/noc-ops",
    category: "Internal",
    description: "Channel komunikasi utama tim NOC — alert, diskusi, eskalasi.",
    icon: "message-square",
  },
  {
    id: "link-009",
    label: "Telegram Bot Alert",
    url: "https://t.me/noc_alert_bot",
    category: "Internal",
    description: "Bot Telegram untuk notifikasi alert monitoring real-time.",
    icon: "bot",
  },
  {
    id: "link-010",
    label: "Vendor Portal — Telkomsel",
    url: "https://vendor.telkomsel.com/partner",
    category: "Vendor",
    project: "EPC Core",
    description: "Portal vendor untuk akses dokumentasi API dan support ticket.",
    icon: "building",
  },
  {
    id: "link-011",
    label: "Share Drive NOC",
    url: "https://drive.google.com/drive/folders/noc-shared",
    category: "Internal",
    description: "Folder bersama: template report, config files, VPN profiles.",
    icon: "folder",
  },
  {
    id: "link-012",
    label: "Netbox DCIM",
    url: "https://netbox.internal.tritronik.com",
    category: "Internal",
    description: "Data Center Infrastructure Management — IP, rack, device inventory.",
    icon: "server",
  },
];

/* ═══════════════════════════════════════════════
   SEED DATA — KONTAK ESKALASI
═══════════════════════════════════════════════ */

export const seedEscalationContacts: EscalationContact[] = [
  // ── EPC Core ──
  {
    id: "esc-001",
    project: "EPC Core",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
    notes: "Monitoring & triage awal.",
  },
  {
    id: "esc-002",
    project: "EPC Core",
    level: "L2",
    name: "Ahmad Fauzi",
    role: "L2 Specialist — EPC",
    phone: "+62 812-3456-7890",
    email: "ahmad.fauzi@tritronik.com",
    channel: "Teams: NOC-Escalation",
    responseTarget: "≤ 15 menit",
  },
  {
    id: "esc-003",
    project: "EPC Core",
    level: "L3",
    name: "Rudi Hermawan",
    role: "Infrastructure Engineer",
    phone: "+62 811-2233-4455",
    email: "rudi.hermawan@tritronik.com",
    responseTarget: "≤ 30 menit",
  },
  // ── SM / ActiveMQ ──
  {
    id: "esc-004",
    project: "SM/ActiveMQ",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
  },
  {
    id: "esc-005",
    project: "SM/ActiveMQ",
    level: "L2",
    name: "Budi Santoso",
    role: "L2 Specialist — Middleware",
    phone: "+62 813-5566-7788",
    email: "budi.santoso@tritronik.com",
    channel: "Teams: Middleware-Support",
    responseTarget: "≤ 15 menit",
  },
  // ── B2B / Kafka ──
  {
    id: "esc-006",
    project: "B2B",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
  },
  {
    id: "esc-007",
    project: "B2B",
    level: "L2",
    name: "Dimas Prasetyo",
    role: "L2 Specialist — Integration",
    phone: "+62 815-9900-1122",
    email: "dimas.prasetyo@tritronik.com",
    channel: "Teams: B2B-Support",
    responseTarget: "≤ 15 menit",
  },
  {
    id: "esc-008",
    project: "B2B",
    level: "Vendor",
    name: "Vendor B2B Support",
    role: "Vendor Technical Support",
    email: "support@vendor-b2b.com",
    channel: "Ticket Portal",
    responseTarget: "Per SLA (4 jam)",
    notes: "Buat tiket via vendor portal. CC ke L2 Specialist.",
  },
  // ── USIEM / Graylog ──
  {
    id: "esc-009",
    project: "USIEM",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
  },
  {
    id: "esc-010",
    project: "USIEM",
    level: "L2",
    name: "Sari Wulandari",
    role: "L2 Specialist — Security",
    phone: "+62 817-3344-5566",
    email: "sari.wulandari@tritronik.com",
    channel: "Teams: SIEM-Ops",
    responseTarget: "≤ 15 menit",
  },
  // ── UNEM ──
  {
    id: "esc-011",
    project: "UNEM",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
  },
  {
    id: "esc-012",
    project: "UNEM",
    level: "L2",
    name: "Eko Widodo",
    role: "L2 Specialist — Network",
    phone: "+62 819-7788-9900",
    email: "eko.widodo@tritronik.com",
    responseTarget: "≤ 15 menit",
  },
  // ── DM ──
  {
    id: "esc-013",
    project: "DM",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
  },
  {
    id: "esc-014",
    project: "DM",
    level: "L2",
    name: "Fajar Nugroho",
    role: "L2 Specialist — Device Management",
    phone: "+62 816-1122-3344",
    email: "fajar.nugroho@tritronik.com",
    responseTarget: "≤ 20 menit",
  },
  // ── MB (Mobile Banking) ──
  {
    id: "esc-015",
    project: "MB",
    level: "L1",
    name: "Tim Shift NOC",
    role: "Operator NOC",
    channel: "Central Tracking Dashboard",
    responseTarget: "Langsung",
  },
  {
    id: "esc-016",
    project: "MB",
    level: "L2",
    name: "Rina Permata",
    role: "L2 Specialist — Mobile Services",
    phone: "+62 818-4455-6677",
    email: "rina.permata@tritronik.com",
    responseTarget: "≤ 15 menit",
  },
];
